### ISSUE TITLE
Turning off orthographic camera mode does not set camera clipping distance back

### ISSUE THREAD

**Issue by ja231c** [Perchik71/Creation-Kit-Platform-Extended#10]
This results in perspective mode being basically unusable after orthographic mode was activated.

Also, the render window title doesn't change when toggling between camera modes, only when reloading the cell;

Also, is there any way to change the scroll zoom speed in orthographic mode? It is extremely fast, much faster than in perspective mode, making it difficult to use.

Not sure if any of this got changed in 0.2 build 88 as that one doesn't even work for me, like the other issue says.

**Comment by Perchik71** [comment]
Also, is there any way to change the scroll zoom speed in orthographic mode?
![2024-02-19_07-38-05](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/cabfa4a6-bb7e-4fb1-8b2f-7c4a7bb2b0ed)
Also, the render window title doesn't change when toggling between camera modes, only when reloading the cell;
`Just a click is enough, but I'll take a look`
This results in perspective mode being basically unusable after orthographic mode was activated.
`It works fine for me`

**Comment by ja231c** [comment]
Orthographic camera never enabled (0 not pressed):
![no_ortho](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/68137237/2bc1ba9e-888a-4bcf-bb3b-c9bb18abdf3c)
Orthographic camera enabled (0 pressed once):
![ortho](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/68137237/1826776e-fbc2-451d-893a-62d5727fd78b)
Orthographic camera disabled (0 pressed twice):
![ortho_off](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/68137237/8f68970f-105b-4ffc-814d-05bb3cf9067f)

**Comment by Perchik71** [comment]
Bethesda fixed in 1378, closed
