### ISSUE TITLE
Multiple Errors and unable to Facegen Export

### ISSUE THREAD

**Issue by joshuaadriel86** [Perchik71/Creation-Kit-Platform-Extended#101]
Was sent here by Perchik71. 

The Cell View Window is not working properly for me. The "Loaded at Top/Visible Only" button switches back and forth rapidly when the cursor passes over it, but more importantly, the "Show Only Active Cell" and the "Show Only Active Objects" do not work at all and I know that it did work for me in previous CKPE versions. Ctrl F4 for Face Gen creation/export does not work for me either as it freezes the CK and makes it "Not Responding." I can confirm that Face Gen Export through Ctrl F4 (as opposed to enabling on save) works without this mod installed (1 NPC in 2-3 seconds) and that in previous CKPE versions, like the 0.4-b59 or so, it worked for me surprisingly quick (more than 20 NPCs in about 10 seconds).

Log is showing multiple errors:
[ERROR] The dependent module "D3D11 Patch" was not detected: "Render Window"
[ERROR] the dependent module "Render Window" has not been enabled, this module will not be enabled: "Object Window"
[ERROR] the dependent module "Object Window" has not been enabled, this module will not be enabled: "Main Window"
[ERROR] the dependent module "Main Window" has not been enabled, this module will not be enabled: "Cell View Window"
[ERROR] The dependent module "Main Window" was not detected: "Cell View Window"
[ERROR] the dependent module "Cell View Window" has not been enabled, this module will not be enabled: "Fix CellView Object List"
[ERROR] The dependent module "Main Window" was not detected: "Progress Window"
[ERROR] The dependent module "Main Window" was not detected: "Update UI When Fog Toggled"

I have an Alienware from 2021 and it has Windows 10 and DX 12. Skyrim AE and CK are both the latest version and purchased and run from Steam.

Perchik71 suggested to delete *Filter.txt, but no such file exists in my Skyrim SE folder.

CKPE full log:

Open the config ini file: CreationKitPlatformExtended.ini
Current time: Monday 30 Dec 2024 08:06:15 PM Eastern Standard Time
CRC32 executable file: 0x9CA7A04B
[WARNING] CRC32 does not match any of the known ones, running a version check by signature
Current CK version: Skyrim Special Edition [v1.6.1378.1]
CKPE Runtime: Initialize (Version: 0.4.0.952, OS: 6.2 Build 9200)
The processor has a number of threads: 16
The processor has a number of logical cores: 16
The processor has a number of physical cores: 8
The processor implements hyper-threads technology: true
The processor supports the SSE 4.1 instruction set: true
The processor supports the AVX 2 instruction set: true
Reading an option in the configuration: CreationKit:bUIClassicTheme
The option is disabled in the configuration: CreationKit:bUIClassicTheme
Reading an option in the configuration: CreationKit:bUIDarkTheme
Module "UI Dark Theme" initializing success
Messages Blacklist: 150
Number of messages whose hash has already been added: 21
Module base: 0000000140000000
Section range ".text": (base: 0000000140001000, end: 0000000142F23200)
Section range ".rdata": (base: 0000000142F24000, end: 00000001437B93C9)
Section range ".data": (base: 00000001437BA000, end: 00000001457B47F1)
Total patches: 119
	Add Change Ref (version 1) -> signature count 3
	Allow Multiple Window And Master (version 1) -> signature count 2
	Allow PlayerKnows Condition (version 1) -> signature count 2
	Allow Save ESM and Master ESP (version 1) -> signature count 12
	Altered Form List And Reference Map (version 1) -> signature count 19
	BNet Convert Unicode String (version 1) -> signature count 1
	BSArchiveManager Modded (version 1) -> signature count 5
	BSShadowDirectionalLight Fix (version 1) -> signature count 1
	Broken Terrain Edit Dlg (version 2) -> signature count 2
	COM (version 1) -> signature count 1
	Cell View Window (version 1) -> signature count 10
	Check D3D11 (version 1) -> signature count 1
	Choose Sound File (version 1) -> signature count 3
	Console (version 1) -> signature count 13
	Crash Dump (version 1) -> signature count 4
	Crash Edit Actor Behavior (version 1) -> signature count 1
	Crash FlowChartX (version 2) -> signature count 1
	Crash HairKS (version 1) -> signature count 2
	Crash Inventory Iterators (version 1) -> signature count 10
	Crash MHDT More Than 70 (version 1) -> signature count 4
	Crash Merge Forms (version 1) -> signature count 12
	Crash Nullptr FaceGen (version 1) -> signature count 2
	Crash Sort Function (version 1) -> signature count 1
	Crash Test Radius (version 1) -> signature count 6
	Crash Upload BNet Mod With Archive (version 1) -> signature count 1
	Crash Using More 16 NPC For FaceGen (version 1) -> signature count 2
	Crash after Multiple Masters Warning (version 1) -> signature count 2
	D3D11 Patch (version 1) -> signature count 1
	Data Window (version 1) -> signature count 1
	Deferred dialog loading (version 1) -> signature count 18
	Disable Assertion (version 2) -> signature count 2
	Enable Game Button To VC (version 1) -> signature count 2
	Enable State Parent Workaround (version 1) -> signature count 5
	FaceGen (version 1) -> signature count 15
	File in use (version 1) -> signature count 1
	Fix ATXT params sections (version 1) -> signature count 1
	Fix Actor Dlg (version 1) -> signature count 1
	Fix BGSEntryPointFunctionDataTwoValue (version 1) -> signature count 2
	Fix Bright Light Color (version 1) -> signature count 2
	Fix CellView Object List (version 1) -> signature count 4
	Fix Class Dlg (version 1) -> signature count 2
	Fix Crash Duplicate Form (version 1) -> signature count 1
	Fix Crash In Armor Addon (version 1) -> signature count 4
	Fix Crash Lighting Shader (version 1) -> signature count 1
	Fix Crash MakeXYZCircles (version 1) -> signature count 1
	Fix Crash PluginTXT (version 1) -> signature count 1
	Fix Crash TabControl (version 1) -> signature count 1
	Fix Data Dlg with PluginTXT (version 1) -> signature count 2
	Fix Dialogue Branch (version 1) -> signature count 1
	Fix FormIDs In Load File (version 1) -> signature count 8
	Fix Icons Script Prop (version 1) -> signature count 1
	Fix Intersection Triangle (version 2) -> signature count 2
	Fix Load More 32K Animation (version 1) -> signature count 1
	Fix Memory Leak ActorDlg (version 1) -> signature count 1
	Fix Move to topic (version 1) -> signature count 1
	Fix MusicTrack Form (version 1) -> signature count 1
	Fix Object Palette (version 1) -> signature count 3
	Fix Race Dlg (version 1) -> signature count 1
	Fix Remote Desktop (version 1) -> signature count 1
	Fix RenderPass (version 1) -> signature count 4
	Fix Selected Package Data (version 1) -> signature count 1
	Fix Spell Dlg (version 1) -> signature count 1
	Fix Unable To Find Variable (version 1) -> signature count 1
	Fix VTXT params sections (version 1) -> signature count 1
	Fix Vertex Normals (version 1) -> signature count 2
	Fix Water In Ortho mode (version 1) -> signature count 1
	Fix Water Type (version 1) -> signature count 5
	Fix a spell effect duration (version 1) -> signature count 2
	FlowChartX Library (version 2) -> signature count 1
	INI Cache Data (version 1) -> signature count 1
	Ignore Ground Height Test (version 1) -> signature count 1
	Increase the maximum navmesh (version 1) -> signature count 2
	Load .DDS File (version 1) -> signature count 2
	Load Optimization (version 2) -> signature count 11
	Main Window (version 1) -> signature count 5
	Memory Leak In Peview Window (version 2) -> signature count 5
	Memory Leak class BSString (version 1) -> signature count 1
	Memory Manager (version 1) -> signature count 10
	Misc (version 1) -> signature count 1
	Misc Messages (version 1) -> signature count 1
	NavMesh Info Map (version 1) -> signature count 1
	NavMesh Pseudo Delete (version 1) -> signature count 9
	NavMesh Window (version 1) -> signature count 1
	NiCollisionObject Cloned Warning (version 1) -> signature count 2
	NiSkinInstance Fix (version 1) -> signature count 3
	Object Window (version 2) -> signature count 2
	Papyrus Editor Limit (version 1) -> signature count 1
	Progress Window (version 1) -> signature count 3
	Quit Handler (version 1) -> signature count 3
	Re-enable fog rendering (version 2) -> signature count 18
	Re-enable land shadows (version 1) -> signature count 2
	Ref Link Geometry Hang Workaround (version 1) -> signature count 2
	Remove Useless Messages (version 1) -> signature count 14
	Rename Creation Kit App (version 1) -> signature count 1
	Render Window (version 1) -> signature count 3
	Render Window 60 FPS (version 1) -> signature count 4
	Replace BSPointerHandle And Manager (version 1) -> signature count 27
	Response Ignore Max (version 1) -> signature count 1
	Runtime Optimization (version 1) -> signature count 5
	Show Reload Shaders Always (version 1) -> signature count 1
	Skip Topic Info Validation (version 1) -> signature count 1
	Spell Enable Casting And Delivery Always (version 1) -> signature count 2
	Stable Sort For Perks (version 1) -> signature count 1
	TESDataHandler (version 1) -> signature count 2
	TESModelTextureSwap Correctly Load (version 1) -> signature count 1
	TESParameters CTDA (version 1) -> signature count 2
	Threads (version 1) -> signature count 1
	UI (version 1) -> signature count 1
	UI Classic Theme (version 1) -> signature count 1
	UI Dark Theme (version 1) -> signature count 1
	UI Dark Theme Additional (version 1) -> signature count 12
	UI Hotkeys (version 1) -> signature count 2
	UnEquip Sound (version 1) -> signature count 1
	Unicode (version 1) -> signature count 11
	Update UI When Fog Toggled (version 1) -> signature count 2
	Upload PS4 modded without assets (version 1) -> signature count 3
	VCBitArray (version 1) -> signature count 4
	Version Control Merge Workaround (version 1) -> signature count 2
	Weapon Critical Effect (version 1) -> signature count 6
Total signatures: 430
DIALOG: Open archive "CreationKitPlatformExtended_SSE_Dialogs.pak"
The dialog has been added: "122.json"
The dialog has been added: "141.json"
The dialog has been added: "162.json"
The dialog has been added: "175.json"
The dialog has been added: "220.json"
The dialog has been added: "494.json"
Module "BGSPerkRankArray" rejected the query, most likely does not support the version of the editor or platform.
Module "Crash CCC Files" rejected the query, most likely does not support the version of the editor or platform.
Module "Crash Duplicate Worldspace" rejected the query, most likely does not support the version of the editor or platform.
Module "D3D11 Patch" rejected the query, most likely does not support the version of the editor or platform.
Module "Fix NavMesh" rejected the query, most likely does not support the version of the editor or platform.
Module "Fix Reverb Parameters" rejected the query, most likely does not support the version of the editor or platform.
Module "LipGen" rejected the query, most likely does not support the version of the editor or platform.
Module "New Format 1.71" rejected the query, most likely does not support the version of the editor or platform.
Module "Replace BSPointerHandle And Manager" initializing success
Module "Add Change Ref" initializing success
Module "Allow Multiple Window And Master" initializing success
Module "Allow PlayerKnows Condition" initializing success
Module "Console" initializing success
Module "Allow Save ESM and Master ESP" initializing success
Module "Altered Form List And Reference Map" initializing success
Module "BNet Convert Unicode String" initializing success
Reading an option in the configuration: CreationKit:bOwnArchiveLoader
Open the config ini file: CreationKit.ini
Open the config ini file: CreationKitCustom.ini
Module "BSArchiveManager Modded" initializing success
Module "BSShadowDirectionalLight Fix" initializing success
Module "Broken Terrain Edit Dlg" initializing success
Module "Re-enable fog rendering" initializing success
[ERROR] The dependent module "D3D11 Patch" was not detected: "Render Window"
[ERROR] the dependent module "Render Window" has not been enabled, this module will not be enabled: "Object Window"
[ERROR] the dependent module "Object Window" has not been enabled, this module will not be enabled: "Main Window"
[ERROR] the dependent module "Main Window" has not been enabled, this module will not be enabled: "Cell View Window"
Module "Check D3D11" initializing success
Module "Choose Sound File" initializing success
Reading an option in the configuration: CreationKit:bGenerateCrashdumps
Module "Crash Dump" initializing success
Module "Crash FlowChartX" initializing success
Module "Crash HairKS" initializing success
Module "Crash Inventory Iterators" initializing success
Module "Crash MHDT More Than 70" initializing success
Reading an option in the configuration: CreationKit:bOverlapsGenerateONAM
Module "Crash Merge Forms" initializing success
Module "Crash Nullptr FaceGen" initializing success
Module "Crash Sort Function" initializing success
Module "Crash Test Radius" initializing success
Module "Crash Upload BNet Mod With Archive" initializing success
Module "Crash Using More 16 NPC For FaceGen" initializing success
Module "Crash after Multiple Masters Warning" initializing success
Module "Data Window" initializing success
Module "Deferred dialog loading" initializing success
Reading an option in the configuration: CreationKit:bDisableAssertions
The option is disabled in the configuration: CreationKit:bDisableAssertions
Module "Enable Game Button To VC" initializing success
Reading an option in the configuration: CreationKit:bEnableStateParentWorkaround
The option is disabled in the configuration: CreationKit:bEnableStateParentWorkaround
Disabling automatic calling FaceGen
Disabling export FaceGen .TGA files
Module "FaceGen" initializing success
Module "File in use" initializing success
Module "Fix ATXT params sections" initializing success
Module "Fix Actor Dlg" initializing success
Module "Fix BGSEntryPointFunctionDataTwoValue" initializing success
Module "Fix Bright Light Color" initializing success
[ERROR] The dependent module "Main Window" was not detected: "Cell View Window"
[ERROR] the dependent module "Cell View Window" has not been enabled, this module will not be enabled: "Fix CellView Object List"
Module "Fix Class Dlg" initializing success
Module "Fix Crash Duplicate Form" initializing success
Module "Fix Crash In Armor Addon" initializing success
Module "Fix Crash Lighting Shader" initializing success
Module "Fix Crash MakeXYZCircles" initializing success
Module "Fix Crash PluginTXT" initializing success
Module "Fix Crash TabControl" initializing success
Module "Fix Data Dlg with PluginTXT" initializing success
Module "Fix Dialogue Branch" initializing success
Module "Fix FormIDs In Load File" initializing success
Module "Fix Icons Script Prop" initializing success
Module "Fix Intersection Triangle" initializing success
Module "Fix Load More 32K Animation" initializing success
Module "Fix Memory Leak ActorDlg" initializing success
Module "Fix Move to topic" initializing success
Module "Fix MusicTrack Form" initializing success
Module "Fix Object Palette" initializing success
Module "Fix Race Dlg" initializing success
Module "Fix Remote Desktop" initializing success
Module "Fix RenderPass" initializing success
Module "Fix Selected Package Data" initializing success
Module "Fix Spell Dlg" initializing success
Module "Fix Unable To Find Variable" initializing success
Module "Fix VTXT params sections" initializing success
Module "Fix Vertex Normals" initializing success
Module "Fix Water In Ortho mode" initializing success
Module "Fix Water Type" initializing success
Module "Fix a spell effect duration" initializing success
Module "FlowChartX Library" initializing success
Reading an option in the configuration: CreationKit:bINICache
Module "INI Cache Data" initializing success
Reading an option in the configuration: CreationKit:bIgnoreGroundHeightTest
The option is disabled in the configuration: CreationKit:bIgnoreGroundHeightTest
Module "Increase the maximum navmesh" initializing success
Module "Load .DDS File" initializing success
Module "Load Optimization" initializing success
Module "Memory Leak In Peview Window" initializing success
Module "Memory Leak class BSString" initializing success
Physical Memory (Total: 31.8 Gb, Available: 15.4 Gb)
Memory (Total: 46.3 Gb, Available: 23.2 Gb)
Module "Memory Manager" initializing success
Module "Misc Messages" initializing success
Module "NavMesh Info Map" initializing success
Reading an option in the configuration: CreationKit:bNavMeshPseudoDelete
The option is disabled in the configuration: CreationKit:bNavMeshPseudoDelete
Module "NavMesh Window" initializing success
Module "NiCollisionObject Cloned Warning" initializing success
Module "NiSkinInstance Fix" initializing success
Module "Papyrus Editor Limit" initializing success
[ERROR] The dependent module "Main Window" was not detected: "Progress Window"
Module "Quit Handler" initializing success
Module "Re-enable land shadows" initializing success
Module "Remove Useless Messages" initializing success
Module "Rename Creation Kit App" initializing success
Module "Render Window 60 FPS" initializing success
Module "Response Ignore Max" initializing success
Module "Show Reload Shaders Always" initializing success
Reading an option in the configuration: CreationKit:bSkipTopicInfoValidation
Module "Skip Topic Info Validation" initializing success
Module "Spell Enable Casting And Delivery Always" initializing success
Module "Stable Sort For Perks" initializing success
Module "TESDataHandler" initializing success
Module "TESModelTextureSwap Correctly Load" initializing success
Module "TESParameters CTDA" initializing success
ProcessMask: 0xFFFF
SystemMask: 0xFFFF
CKPE_ThreadMain 10056
Module "Threads" initializing success
Module "UI" initializing success
Reading an option in the configuration: CreationKit:bUIClassicTheme
The option is disabled in the configuration: CreationKit:bUIClassicTheme
Module "UI Dark Theme Additional" initializing success
Reading an option in the configuration: CreationKit:bUIHotkeys
Module "UI Hotkeys" initializing success
Module "UnEquip Sound" initializing success
Reading an option in the configuration: CreationKit:bUnicode
The option is disabled in the configuration: CreationKit:bUnicode
[ERROR] The dependent module "Main Window" was not detected: "Update UI When Fog Toggled"
Module "Upload PS4 modded without assets" initializing success
Module "VCBitArray" initializing success
Reading an option in the configuration: CreationKit:bVersionControlMergeWorkaround
The option is disabled in the configuration: CreationKit:bVersionControlMergeWorkaround
Module "Weapon Critical Effect" initializing success
Modules installed: 99 from 109
Plugins installed: 0 from 0

**Comment by Perchik71** [comment]
Reason: OS: 6.2 Build 9200
Use old ckpe.

**Comment by joshuaadriel86** [comment]
But I don't run Win 8 6.2 Build 9200; I have Win 10 19045.5247 (as displayed with run->winver). Why would the CKPE think I'm running Win 8?

**Comment by joshuaadriel86** [comment]
I checked for Win 10 OS Updates, did System File Checker (SFC) Scan and DISM Tool, and Checked Environment Variables, as suggested and guided by AI, and CKPE logs still shows 6.2 Build 9200.

**Comment by joshuaadriel86** [comment]
AI analysis and suggestion:

Module Rejections: Several modules were rejected, likely due to compatibility issues with the editor or platform version. This includes modules like BGSPerkRankArray, Crash CCC Files, D3D11 Patch, and more.

Successful Initializations: Many modules successfully initialized, including Replace BSPointerHandle And Manager, Console, FaceGen, Memory Manager, and more.

Errors: There are errors related to dependent modules not being detected, such as Render Window, Object Window, Main Window, and Cell View Window. This cascade of errors could be affecting the program's overall functionality.

Memory Information: Your system's memory is correctly identified, and there seems to be plenty of available memory.

Given these points, the misidentification of the OS version might be causing some modules to reject queries or not initialize properly. Here are a few additional steps you can take:

Contact CKPE Support: Given the specific nature of these errors, the CKPE support team will likely have the most relevant advice. They might provide a patch or further troubleshooting steps to address these issues.

Check for Program-Specific Updates: Ensure that all related components or plugins for CKPE are up-to-date.

Run as Administrator: Continuously running the program as an administrator might help alleviate some permission-related issues.

These detailed errors suggest that the program's compatibility with your current setup is the root cause. Reaching out to CKPE support with this log might expedite a resolution.

**Comment by Perchik71** [comment]
ntdll.RtlGetVersion() it is currently a reliable way to identify Windows.
Well, I heard you, but it's preferable for you to use the old version now.

**Comment by joshuaadriel86** [comment]
I bought my computer brand new directly from Best Buy in 2021, so who knows, but everything I have searched in my computer shows Windows 10 Home.

slmgr /dlv shows:

Software licensing service version: 10.0.19041.5247
Name: Windows(R) Core Edition (aka Home)
Description: Windows (R) Operating System, OEM_DM channel.

Winver, slui.exe, and This PC->Properties show "Windows is activated," licensed to me, and Windows 10 Home Version 22H2 OS build 19045.5247.

Not to mention that I run heavy new programs like Adobe Creative Cloud with no problems.

Still, thank you for your responses. If I have the latest Skyrim AE and CK, which older version of CKPE should I use?

**Comment by Perchik71** [comment]
840-rc1

**Comment by joshuaadriel86** [comment]
So, essentially, I can't Facegen using CKPE unless I use an older version of the CK?

Can't thank you enough for taking the time to help me.
