### ISSUE TITLE
Request: More color themes for the CK

### ISSUE THREAD

**Issue by TheLovelyServine** [Perchik71/Creation-Kit-Platform-Extended#12]
It's me again, asking for another enhancement, would it be possible to add more color themes like red, blue, green, or yellow for variety and so everyone can use their favorite color? I would like light theme variants and dark theme variants, (ex. dark blue, light blue, dark red, light red.)

Colors I hope to see:

Red, blue, green, yellow, pink, purple, brown, teal.

It would be so cool if this was possible, because, while I like the dark theme, the CK would look nice in red or blue in my opinion.

**Comment by Perchik71** [comment]
It takes a lot of time to do something well, and I'm alone. Although I was thinking about developing **`uitheme`**, separating its data from the main code. And then let the users paint as they like.

**Comment by Perchik71** [comment]
Added.

**Comment by TheLovelyServine** [comment]
Where can I download?
