### ISSUE TITLE
"Ground height test failed" during navmesh generation in a Worldspace with "No Landscape" flag

### ISSUE THREAD

**Issue by ja231c** [Perchik71/Creation-Kit-Platform-Extended#13]
<img width="283" alt="ground_height_test_failed" src="https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/68137237/708b723b-efa2-483d-968f-b9f122e2cc6f">

This box appears continuously when attempting to generate navmesh in Worldspace with a "No Landscape" flag.

The navmesh generation stops when the box appears, the user must close or OK all of those boxes for the navmesh to actually generate in a Worldspace with this flag.

The problem is - the Ground height test will always fail in a Worldspace with "No Landscape" flag since there is no land, this results in the box appearing I believe 4096 times and needing to be closed those 4096 times to actually get a navmesh.

Removing the "No Landscape" flag allows the navmesh generation to work.

**Comment by Perchik71** [comment]
In itself, the question is very interesting, but why do it without a landscape? How is it different? What is the practical benefit of this?

**Comment by ja231c** [comment]
I have worldspaces with no landscape and no need for landscape in which I need navmesh.

I want it to not show the message or window about this when there is a "No Landscape" flag, any messages about the ground height test are completely irrelevant with this flag.
