### ISSUE TITLE
Add "Replace Base" for References.

### ISSUE THREAD

**Issue by Delta012** [Perchik71/Creation-Kit-Platform-Extended#14]
It would be a great quality of life if we could change the assets of already defined References in the Creation Kit, without the need to do that in xEdit.

**Comment by Delta012** [comment]
I mean, if I want to change the look of an already placed tree, for example, I need to do that with xEdit, and that's a bit tricky and tedious to do without the reference window in CK

**Comment by robertgk2017** [comment]
You can do that in the CK already, just edit the Reference itself?

**Comment by ja231c** [comment]
I think he wants to change the Base Object of a Reference without removing and replacing it, as in, he's got a reference with Base Object of "SomeRandomTree01" and he wants to replace it with "SomeOtherRandomTree03", without deleting and placing it again, xEdit can easily do that, CK cannot or I'm a moron and haven't figured out how to change the Base Object of a Reference.

**Comment by Delta012** [comment]
Yes, I meant exactly what ja231c said

**Comment by Perchik71** [comment]
Alt+Scroll mouse (middle button). It changes just like in a fairy tale. Only 1.6 and higher.

**Comment by ja231c** [comment]
While that does work - it's only useful if you want to change to a similarly named object.

In many cases it would be better if we could replace Selected Objects with Object from the Object Window (or the Object Palette), maybe a new option in context menu of Objects in the Object Window/Object Palette, named "Replace Selected".

**Comment by Perchik71** [comment]
[Added](https://github.com/Perchik71/Creation-Kit-Platform-Extended/commit/76636231fb2a097ff4e8b19efbab06ca157ce90f)
