### ISSUE TITLE
Editing extra world items that were NOT edited.

### ISSUE THREAD

**Issue by Woodfuzzy** [Perchik71/Creation-Kit-Platform-Extended#15]
This has broke 2 mods so far!
Issue:
Mod 1: CWSS patch that ONLY edits custom interior cells and 1 exterior cell (DunmoreFarm)
The patch disables current bathroom items and adds only CWSS bathroom items. Nothing else is touched.

Edited a couple custom interior cells, saved, exited.
Opened in xEdit, found 4 exterior cells had also been edited.
Custom Cell, 00ApolloSpot, 
Vanilla cell, NukaWorldNukaTownUSA03,  NukaWorldNukaTownUSA07
All with StaticCollectionPivotDummy [STAT:00035812]
Vanilla cell: NukaWorldNukaTownUSA09
With Tire03HollowStatic "Tire" [STAT:000DD3C9]
Also added a bunch of Reference Group records

Mod 2: NPC Patch. Edits ONLY NPCs. 
Edited a package on an NPC, saved exited. Never loaded a any cells.
Pretty much exactly as Mod 1. Bunch of world cells edited with the StaticCollectionPivotDummy [STAT:00035812]

I've included a broken copy of the CWSS patch, just in case it's useful.

[Nuka Ride CWSS WORLD Patch.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/14074744/Nuka.Ride.CWSS.WORLD.Patch.zip)

**Comment by Perchik71** [comment]
The mod itself is unlikely to help me, it has a lot of dependencies that I don't have at all. I'll make a couple of mods manually.

**Comment by Perchik71** [comment]
I haven't been able to reproduce it yet. Was it in Vanilla?
![2024-01-28_15-16-21](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/4373ec39-f794-4220-b80d-77c8bb766db9)

**Comment by Perchik71** [comment]
[winhttp.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/14076008/winhttp.zip)
The only thing that comes to mind, and it can somehow affect it, is the optimization patch.
Here is the version without the optimized download patch, try it after removing the excess from the mods.

**Comment by Woodfuzzy** [comment]
Tried both and no difference.
Don't know why, but just loading the patch and saving, no edits, causes it to grab the Reference Group and the extra Worldspace cells.
This is what it "should" look like.
<img width="678" alt="Desktop Screenshot 2024 01 28 - 11 32 06 37" src="https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/157910612/3c752507-67ad-4cbe-8bf7-eb0c7be722cb">

This is after loading and saving.
<img width="677" alt="Desktop Screenshot 2024 01 28 - 11 38 09 99" src="https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/157910612/e8dac657-8a08-4bac-b2f8-764aa3d8d77a">

**Comment by Perchik71** [comment]
I had to download it all. I removed the ref group from the mod. And he successfully created them again. Well, let's look for it.

**Comment by Perchik71** [comment]
In general, as soon as I delete everything unnecessary and try to save it in vanilla, it just deletes the Nuke Ride master file from dependencies. And in general, he swears a lot about Nuke Ride mod. As soon as it is deleted, the generation of unnecessary forms stops. Also, if delete some patches, the behavior remains vanilla, and after saving this master file is removed.

**Comment by Perchik71** [comment]
[winhttp.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/14077706/winhttp.zip)
You can use this for now, while I think what should I do with this SkipTopicInfoValidationPatch patch.
