### ISSUE TITLE
CK completely messed up

### ISSUE THREAD

**Issue by khirasier** [Perchik71/Creation-Kit-Platform-Extended#2]
![Untitled](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/24450142/b37ec8ac-aeb6-45fe-87d7-76a4419cc8fe)
simply put, the ck extended makes it look like this and you cant read anything

**Comment by khirasier** [comment]
ok so it looks fine if you launch it with dark mode enabled but if it isnt it makes it look like that

**Comment by Perchik71** [comment]
Fixed. Thx.
