### ISSUE TITLE
Causes severe lag and unresponsiveness to PC to near freezing randomly after doing anything in additional windowa

### ISSUE THREAD

**Issue by TheLovelyServine** [Perchik71/Creation-Kit-Platform-Extended#20]
My PC seems to suffer from severe lag from opening and using additional windows, like when editing an item. This didn't happen before and a more recent version seems to be causing it. I don't remember which one. My PC can't do anything when this happens and I have to perform a reset after the CK causes the lag. It's eating up my RAM.

Edit: Installed newest version after reset, so let me see how that goes.

**Comment by Perchik71** [comment]
Miraculously, nothing happens. Although I do not observe such a problem.

**Comment by TheLovelyServine** [comment]
The bug happened again, as of writing, I'm resetting my PC

**Comment by Perchik71** [comment]
Not relevant
