### ISSUE TITLE
Dragging vertices in NavMesh Mode when Snap to Grid is enabled requires a certain mouse velocity to actually move the vertex

### ISSUE THREAD

**Issue by ja231c** [Perchik71/Creation-Kit-Platform-Extended#21]
This is extremely annoying and makes it very difficult to move vertices to precise positions.

If you move the mouse too slow it won't move the vertex at all.
If you move the mouse too fast it'll move the vertex multiple snap positions over.

This annoying mouse acceleration requirement appears to only exist in NavMesh mode when Snap to Grid is enabled, with Snap to Grid disabled or outside of NavMesh mode everything works properly.

**Comment by robertgk2017** [comment]
you shouldn't be using snap to grid in navmesh mode at all.   or at the very least you ought to reduce your snap amount in the preferences.

**Comment by ja231c** [comment]
Not sure why I shouldn't use it, it works just fine and does exactly what it should, other than the damn mouse velocity problem that is.

**Comment by robertgk2017** [comment]
The distances your moving verts around, for the most part, will be smaller than the distance between snap points.  So it's just not practical.  Just turn snap to grid off and free move them.

**Comment by Perchik71** [comment]
I can't fix it.

**Comment by ja231c** [comment]
That's sad, it is very annoying and makes working with navmeshes considerably harder.

**Comment by robertgk2017** [comment]
You can just turn off snap to grid.  And it works just fine.  This is a non-issue.

**Comment by ja231c** [comment]
Alright, it is a minor issue; I can just turn off snapping, and it does work but there's something about vertices not being aligned that annoys me, especially on exterior cell borders, definitevely more than it should.
