### ISSUE TITLE
Rotate in Preview Window bound to Right Mouse Button.

### ISSUE THREAD

**Issue by CyborgArmGun** [Perchik71/Creation-Kit-Platform-Extended#24]
For some reason The Model Data / Preview Window's Rotate key is switched to the right mouse button? It's supposed to be left click drag. Right drag brings up the Preferences menu, which defeats the point of rotation.

I don't know how this was changed in the first place.

**Comment by Perchik71** [comment]
That's right, what kind of game are you talking about? everything is fine in CK 1.6.1130.

**Comment by CyborgArmGun** [comment]
Skyrim Special Edition GOG but with Steam CK 1.6.1130 and the Unofficial Creation Kit Patch + UCKP Patch For Skyrim AE GOG

**Comment by Perchik71** [comment]
With this build, you reduce the version to 1.5.73. I checked original 1.5.73 - fine. There's probably something in your build. I wonder what others will say. 
UCKP - I think it's unnecessary to install on 1.6.1130. And it looks like the author left on his own and abandoned the project.

 It will be necessary to make instructions for GOG somehow. Maybe Robert will help.

**Comment by robertgk2017** [comment]
UCKP delta patches the ck exe back to 1.5.73 so you are not in fact using CK 1.6.1130.   Drop UCKP its not needed anymore.  This seems to be working just fine on my end, reset your CK and report back.

**Comment by CyborgArmGun** [comment]
Fresh install of CK, Platform Extended added directly on top. Issue persists. Left drag moves nothing, Right drag turns, then immediately brings up preferences. Hitting G to remove the ground tile sometimes causes the preview to just flicker.

**Comment by Perchik71** [comment]
upload the CKPE settings here and any of its logs that it generates all the time.

**Comment by CyborgArmGun** [comment]
All from one session to test

[CreationKitPlatformExtended.log](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/14468999/CreationKitPlatformExtended.log)
[d3dx9_42.log](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/14469000/d3dx9_42.log)
[Debug.log](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/14469001/Debug.log)

**Comment by CyborgArmGun** [comment]
FOUND IT what the Shit.

Unticked "Allow Render Window Background Loading" in preferences. What the hell?

**Comment by Perchik71** [comment]
And that it solved your problem?

**Comment by CyborgArmGun** [comment]
Yup It did, camera rotation returned to normal.

I saw no option like that in CreationKitPlatformExtended.ini after a quick search, sadly,

I guess the best action is to put that in the FAQ or some such till another solution come along.

**Comment by Perchik71** [comment]
Added to faq

**Comment by robertgk2017** [comment]
uhh you should very much not disable that cell background loading.  That's gonna make loading into a cell take longer as it will forcibly wait for every single ref to load in before unlocking the UI.
