### ISSUE TITLE
Replace base for select Ref cannot replace more than 1 object at a time

### ISSUE THREAD

**Issue by ja231c** [Perchik71/Creation-Kit-Platform-Extended#25]
I've got very many objects I need to replace with different objects.

**Comment by Perchik71** [comment]
So look at the code, it's done intentionally.

**Comment by ja231c** [comment]
The probability of user error is lower than scrolling through, I know what objects I selected, I know what object I want to replace all of them with; with scrolling I don't know what object it will scroll to next.

Even if it wasn't lower - there's a lot of things in the CK that have high probability of user error.

With a limit of 1 object this feature is almost completely useless.
