### ISSUE TITLE
Unicode support is not perfect

### ISSUE THREAD

**Issue by KKKBoy-cpu** [Perchik71/Creation-Kit-Platform-Extended#27]
As shown in the figure below, the left side is garbled, and the window opened on the right is in normal Chinese. It's best to upgrade the Unicode support plugin. I don't want to use the Windows system settings to support Unicode because it will cause some of the existing txt files on my computer to be garbled.
![CK BUG](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/80685694/63de301e-894e-45cf-97b0-1241c6a0df10)

**Comment by Perchik71** [comment]
Enable dark theme and set charset.

**Comment by Perchik71** [comment]
I voiced it. ListView all Eastern countries need to specify the Charset explicitly. Unfortunately, this is only possible when dark theme mode is enabled. Interception of all windows occurs only in this case and you can change the Charset as you like. 
I'll think about how to describe it better in the settings.
