### ISSUE TITLE
FO4 -GeneratePreCombined error

### ISSUE THREAD

**Issue by feeddanoob** [Perchik71/Creation-Kit-Platform-Extended#28]
Using latest commit, 647a503, the output PSG file is very small, 8 bytes. I suspect it's because the program closing prematurely, like in this screenshot, before the psg file is saved.
![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/38294761/07a0bfd8-331a-4a3f-b64b-3c8b31479cb2)
I am running a batch file with this command in MO2, I left everything default in the ini except for the CK log to be saved.

Edit:
I copied over the files from MO2 to Fallout4\Data folder but I am still getting an 8 byte PSG file

**Comment by Perchik71** [comment]
Oh... thx. I'll fix it.

**Comment by feeddanoob** [comment]
Thank you for the update!
It still seems like I get an 8 byte psg file... It should be more
![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/38294761/a022c7ee-112c-43f5-897c-37894ed851c6)
and
![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/38294761/858d55a5-bfa3-4891-8652-d0667e66f5d4)
for reference on the 8 byte psg file.

**Comment by Perchik71** [comment]
I use: ckpe_loader.exe -GeneratePreCombined:"DLCRobot.esm" clean all
![2024-03-15_20-15-15](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/899539c1-5170-4abd-a310-5fa3d9aa8bd0)

**Comment by Perchik71** [comment]
[CreationKitPlatformExtendedCrash.log](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/14619568/CreationKitPlatformExtendedCrash.log)
Also, periodically, once every 50 CK tries to remove the fucking sky. I will return the instant quit (without message), and check the results.

**Comment by Perchik71** [comment]
File exactly the same volume. I'll leave it like this, this is the final version, until new information appears.

**Comment by feeddanoob** [comment]
I did a clean state on the latest commit. I have no issues with the psg file now. Idk why before it gave a 8 byte psg file... Thank you for being responsive.
