### ISSUE TITLE
FO4 - crash when sorting by Last Combined in Cell View

### ISSUE THREAD

**Issue by emiral85** [Perchik71/Creation-Kit-Platform-Extended#29]
I am pretty sure this was also an issue in CK Fixes (and probably CK). Interior Worldspace is fine, but attempting to sort exterior Worldspaces like Commonwealth or NukaWorld, you can sort by other columns, but attempting to sort by Last Combined will crash CK every time. 
![2024-03-15 17_56_16-Cell View](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/163474000/3113c488-e25d-4e0d-b394-8a586715da28)

**Comment by emiral85** [comment]
I forgot to add, but this was using build 734.

**Comment by Perchik71** [comment]
It would be nice if you attached a dump, since my sorting is still fine.
![2024-03-22_01-49-18](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/6b50fce4-a5da-478c-bcd1-e4a86c5f0640)

**Comment by emiral85** [comment]
Just tested again with Fallout.esm and all DLC, but nothing else. Created empty test plugin within CK, loaded it, and then tried to sort. Interiors sorted fine, but Commonwealth crashed when sorting by Precombined Date. 
[CreationKit.exe_20240401_201318.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/14828197/CreationKit.exe_20240401_201318.zip)

**Comment by Perchik71** [comment]
This is just a function of comparing two forms, one of the forms is null ptr. That is, it simply does not exist. And when comparing, we get an error. Well, I'll look into it this month.

**Comment by Perchik71** [comment]
This is just a function of comparing two forms, one of the forms is null ptr. That is, it simply does not exist. And when comparing, get an error. Well, I'll look into it this month.
