### ISSUE TITLE
facegen settings in the ini

### ISSUE THREAD

**Issue by khirasier** [Perchik71/Creation-Kit-Platform-Extended#3]
the settings in the ini for facegen are reversed, so false = true and true = false

**Comment by khirasier** [comment]
i think topic info validation is reversed aswell

**Comment by Perchik71** [comment]
bSkipTopicInfoValidation and bDisableAutoFaceGen the names of the options themselves reflect the essence of the reversal

**Comment by khirasier** [comment]
> bSkipTopicInfoValidation and bDisableAutoFaceGen the names of the options themselves reflect the essence of the reversal

i mean i had to set bDisableExportNIF and bDisableExportDDS to true for it to export them, when set to false it doesnt export them

**Comment by Perchik71** [comment]
Hmm.. [code](https://github.com/Perchik71/Creation-Kit-Platform-Extended/blob/6a9871067d98fc8811568c395dda37c510697316/Creation%20Kit%20Platform%20Extended%20Core/Patches/SSE/FaceGen.cpp#L84C51-L84C51) obviously, without the truth, the condition will not work, and it works as expected for me. you can try to write 1 or 0.

**Comment by Perchik71** [comment]
[function](https://github.com/Perchik71/Creation-Kit-Platform-Extended/blob/6a9871067d98fc8811568c395dda37c510697316/Creation%20Kit%20Platform%20Extended%20Core/Core/INIWrapper.cpp#L189C20-L189C20)

**Comment by khirasier** [comment]
also for me bDisableExportTGA just doesnt seem to work, whether i set it to true or false it still exports tga files

**Comment by Perchik71** [comment]
Okay, I'll check the signatures

**Comment by Perchik71** [comment]
Damn it. I just forgot to add the module to the manager.

**Comment by Perchik71** [comment]
Fixed FaceGen. Thx.
