### ISSUE TITLE
Request: Navmesh auto gen working faster and is more optimized for performance.

### ISSUE THREAD

**Issue by TheLovelyCroco** [Perchik71/Creation-Kit-Platform-Extended#32]
I got a new PC last month, and it works fine, but navmesh auto gen, be it recast, havok, so on, doesn't seem to finish up, no matter the amount of hours it takes. I would like auto genned navmesh to work faster and be more performance optimized, as I have to reset the CK when it freezes up. It would be very appreciated if you could make navmesh auto gen work better.

**Comment by robertgk2017** [comment]
Autogen is quite literally non functional.  It requires object navmesh to be created for all relevant objects that would need it.  Otherwise you can only effectively use it on a cell that is basically empty.  I would suggest avoiding it completely.

**Comment by ja231c** [comment]
I'm reasonably confident it is functional, I've used it on numerous ocassions, it does tend to create a gigantic mess though, which is sometimes faster to fix than doing the navmesh 100% manually.

@TheLovelyServine what CPU is in your new PC? It shouldn't take hours to complete.

**Comment by TheLovelyServine** [comment]
<img width="296" alt="Screenshot 2024-04-04 212042" src="https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/114426221/ca5ccc34-aa7b-493a-910f-472343589efc">

@ja231c

**Comment by Perchik71** [comment]
@ja231c Not all people have money, opportunities, etc. In general, there is support for SSE4.1 and this is not a bad thing. It also has 4 cores and 4 threads. It's quite workable. Yep, this is far from a gaming option, but it is acceptable. 
@TheLovelyServine As for the request, so far it is an unattainable task, not even RE data for this, not to mention the approximate version of the technology adopted in the algorithm itself. Please do not bother with problems with Navmesh. At least until there are more people or someone more knowledgeable makes a plugin.

**Comment by Perchik71** [comment]
@ja231c Not all people have money, opportunities, etc. In general, there is support for SSE4.1 and this is not a bad thing. It also has 4 cores and 4 threads. It's quite workable. Yep, this is far from a gaming option, but it is acceptable.
@TheLovelyServine As for the request, so far it is an unattainable task, not even RE data for this, not to mention the approximate version of the technology adopted in the algorithm itself. Please do not bother with problems with Navmesh. At least until there are more people or someone more knowledgeable makes a plugin.

**Comment by Perchik71** [comment]
I'll mark it as a request for help.

**Comment by ja231c** [comment]
SSE4.1 has been around for over 15 years, every modern x86 CPU has it. Now, I'm not saying the J4105 is bad for what it is - for a 10 watt chip it is perfectly acceptable - but you can get a much faster used computer for the same amount of money, something with a 4gen i5, maybe even 6gen for example, seriously, I checked - at least here in Poland a J4105 computer costs the same as one with an i5-6400.

**Comment by Perchik71** [comment]
SSE4.1.... you'd be surprised, but I have to check for these instructions, people just get crash because their processor doesn't understand the instructions. You can even check it by reading old mod posts. And so I agree, 15 years old, but no, they are always available only in x64 bit processors. And only starting from year 2012, (only in the top solutions of those times). But it doesn't matter.

**Comment by Perchik71** [comment]
close
