### ISSUE TITLE
Opening DialogView then Crashing

### ISSUE THREAD

**Issue by zenthesize** [Perchik71/Creation-Kit-Platform-Extended#33]
I have done everything from it trying to crash, i done the stuff in the FAQ.  Like Delete the DialogViews folder in Data and run the Creation Kit as an administrator.  i thought i fixed it but opening a pre-extisting dialogue view topic crashed the Creation kit.  I am going to put my dump file as it compressed and not touched. so someone can help me, i appriecate it. thank you

[CreationKit.exe_20240402_124949.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/14836996/CreationKit.exe_20240402_124949.zip)

**Comment by Perchik71** [comment]
this is bug new editor...
![2024-04-03_00-05-05](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/deea4576-2c93-4dea-b4f8-4b94831a5a6d)
![2024-04-03_00-03-02](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/6394c332-8958-478c-93e0-8fbe3c051f39)
maybe i'll fix

**Comment by zenthesize** [comment]
so how do i fix this or get around it, i have no idea what any of that means, i havent even touched the dialogue that much, i just started on it. making a simple custom follower mod with maybe like 6 dungeons and thats it. i can give you the plugin if u want, but i have no idea. i just want to use the dialogue view tab, its easier. any suggestions?

**Comment by Perchik71** [comment]
You do not need to give anything, the problem has been found, it remains to work out a solution

**Comment by zenthesize** [comment]
So basically downgrade the creation kit and use extended platform, and it should be good?
