### ISSUE TITLE
Request: Fix reverb testing

### ISSUE THREAD

**Issue by seanfagan** [Perchik71/Creation-Kit-Platform-Extended#35]
Pressing the "Test" button on the Reverb Parameters window does nothing.

![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/25916387/cf52b8e2-96f9-4726-bc98-3c7159d59eac)

The "Test" button is _supposed_ to open a window where you choose a Sound Descriptor to play as your test sound. You can then press "Play" to hear that sound with the current reverb parameters. I think Bethesda broke this feature with the launch of Special Edition. With no ability to hear your reverb in CK, the only workaround is to move the sliders, save, and launch the game to hear your changes.

To see how reverb testing used to work, skip to 1:00 on this video: https://youtu.be/zQm40oCL06g?t=60

**Comment by Perchik71** [comment]
This fixed bethesda CK 1.6.1130.
