### ISSUE TITLE
Request: Allow edit multiple placed objects at once, and a replace object feature.

### ISSUE THREAD

**Issue by TheLovelyServine** [Perchik71/Creation-Kit-Platform-Extended#36]
I realized something recently after having to manually replace every object in my mod, I need a more snappy way of replacing stuff in the render window instead of deleting the original object and having to reposition the new one in the exact same spot. A QOL feature that just allows you to replace one thing with another would be very helpful. I also want to be able to edit multiple objects in the render at the same time, because it's annoying having to do only one at a time.

**Comment by Perchik71** [comment]
![2024-04-15_22-56-54](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/697fecca-6ba9-4e3b-a267-0f83b8dcd597)
