### ISSUE TITLE
Render window selection issues (double selection)

### ISSUE THREAD

**Issue by tba** [Perchik71/Creation-Kit-Platform-Extended#39]
1) Occasionally when selecting an object in the render window one or more objects behind the intended object will be selected too, as if the selection was a click-and-drag type selection instead of a normal click.

2) Additionally, sometimes when highlighting one or more objects and duplicating them both the originally selected objects and the duplicated objects will remain selected, creating the impression that the duplication did not work. 

I am running into this issue when trying to mod Skyrim SE version 1.6.1170.0/ CK version 1.6.1130.0

**Comment by Oisteri** [comment]
I've had the same issues very frequently ever since I started using this.
To add to this, I've also had a possibly related issue, where sometimes after I select/duplicate an object and rotate it, a previously selected object that is not selected will also rotate. Ctrl + Z / undoing the action will only undo the currently selected objects rotation, not the rotation of the object that was not selected, but still rotated.

**Comment by Jerry-Oak** [comment]
I am experiencing OPs number 2 quite often.
Also when quickly selecting one object after another **without** holding ctrl it often selects both.

**Comment by Jerry-Oak** [comment]
Experiencing number 1 now too. When i duplicate object and then after that move the clone, the clone teleports to the void in front of my own two eyes.

**Comment by gostedlogeka** [comment]
Same issues

**Comment by Nirvana201** [comment]
Happens to me too. When I duplicate and drag, the asset will sometimes go to a random point in the cell. Sometimes the duplication will also drag the previous object I duplicated with the duplicated version of it.

**Comment by Perchik71** [comment]
I'll look at it when I get back to Skyrim.

**Comment by Perchik71** [comment]
I was trying to figure out what the problem was. Multiple duplication works.... hmm.. maybe it has something to do with specific types of forms?
![2024-05-18_11-25-08](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/203e36ac-f224-466b-bef7-02b85be3689a)

**Comment by Perchik71** [comment]
@tba I caught the second case. In my case, I just spammed the mouse in two places.. a release message did not have time to work out.

**Comment by Perchik71** [comment]
@tba @Oisteri @gostedlogeka @Nirvana201 fixed
