### ISSUE TITLE
Recalc Bounds option is broken, when it cannot find the model.

### ISSUE THREAD

**Issue by robertgk2017** [Perchik71/Creation-Kit-Platform-Extended#4]
running the recalc bounds on base records spits out the same data for all records regardless of the bounds of the object in question.

Running it en bulk on skyrim.esm spits out

x1 = -117
y1 = -28
z1 = -117
x2 = 117
y2 = 28
z2 = 117

For all records that have OBND - Object Bounds.

Edit: Wait hang on that was on build 525, let me update to 530 and double check.

Edit2: Still an issue on build 530.

**Comment by Perchik71** [comment]
Rather, it is a bug of the new version of CK.

**Comment by robertgk2017** [comment]
No it works just fine in the vanilla CK

**Comment by Perchik71** [comment]
hmm, it's interesting, then we need to search for the guilty module. I don't remember what it was in the fixes, I'll look for it.

**Comment by Perchik71** [comment]
Could you describe the procedure, I don't know all the possibilities of CK so well.

**Comment by robertgk2017** [comment]
in the object window, right click any object, and select Recalc Bounds.   Object Types that don't have that field won't have that option.

STAT
MSTT
DOOR
ARMO
ARMA
theres a whole list that do have that field.

**Comment by Perchik71** [comment]
I made a recalculation, but in order to save it, I changed the shape beforehand. I can't say anything yet. 
![2023-12-28_22-27-15](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/87a884a5-5ee1-4999-b841-b2dd7830c6e8)

**Comment by robertgk2017** [comment]
hmmm interesting.  Im working on an update to SREX and it consistently outputs the following for the base records we have.
![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/20867977/a699cc83-014a-44c7-a06b-0b46973fb67a)

**Comment by Perchik71** [comment]
So far, all I can say is that I click on "Recalc Bounds" and nothing happens, not even a "*" is placed above the form and file. Something's wrong, I'm going to get into the debugger.

**Comment by Perchik71** [comment]
Well, I looked at it, he recalculated it, looked at it and even considered that it was not necessary to save...
![2023-12-28_23-33-13](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/d05b923e-94a3-428f-88f2-5acf7eed0230)
![2023-12-28_23-38-05](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/107d2bb0-cdce-4690-93a5-dab43b0408e5)
You may have experienced errors by type:
"Bound for object '%s' (%08X) exceeds 32000 unit limits (%.0f,%.0f,%.0f),(%.0f,%.0f,%.0f)."

I will try brazenly to skip this check now and force him to change the file.

**Comment by Perchik71** [comment]
It works fine, it refused to change twice, because the values turned out to be the same. And when I saved them, they didn't change. See the log, what's going on there with all this.

**Comment by robertgk2017** [comment]
Hmmm i wonder if just the meshes i'm using are screwy.  I'll close this for now until i can find out more/narrow it down.

**Comment by robertgk2017** [comment]
Ah i figured it out, I had some file paths setup wrong.  By default the CK should set the bounds to all 0s when it can't find the .nif that is used by the object, which is correct.   With build 530 installed it does the -117, -28, -117, 117, 28, 117 for some reason.

**Comment by Perchik71** [comment]
I'll look at this at my leisure while I sort out other versions of CK priority.
