### ISSUE TITLE
Water appears transparent except for surface ripples/reflections

### ISSUE THREAD

**Issue by kmallon12** [Perchik71/Creation-Kit-Platform-Extended#40]
Water in the render window appears completely transparent, except for surface ripples/reflections:
![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/14884288/d09160a3-154e-4163-91df-dd7984099647)

The expectation is that water should have some opacity/color based on the water type, e.g.:
![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/14884288/36ae8b88-e588-48cf-aaaf-c09c0a173042)

These are my water render settings; I don't believe they are the issue. I've also checked using Nvidia and AMD integrated graphics and the issue persists. The issue is the same for both worldspace water and placed water planes.
![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/14884288/eeda6e4b-c150-4e3f-ab09-1e85c18de1e3)

**Comment by Perchik71** [comment]
Yep, I observe this in 1.6.1130, although it is not present in the old ones.

**Comment by tba** [comment]
Hi, I just want to say I'm seeing this bug as well. Is there a recommended workaround until a fix is available? The water is difficult to position since it is borderline invisible unless I have lights on with a strong enough light to see the ripples.

**Comment by IAmTreyM** [comment]
Seeing the same issue. Extremely difficult to adjust water settings currently without being able to properly see it. Would love a fix whenever possible.

**Comment by robertgk2017** [comment]
Thats not a solution.  We need to be able to use the current version of the CK.

**Comment by IAmTreyM** [comment]
> @tba @IAmTreyM use 1.5 ck version edit: regarding CKPE, I'm currently at starfield.

I'm a Skywind developer working on weathers and interior lighting. I'm certainly not the one who decides which CK version we use. As of now, we need to use the current CK version and I can't see us downgrading in the future. So unfortunately, no I can't just use 1.5 CK version for Skywind development.

**Comment by Perchik71** [comment]
![2024-11-22_04-36-31](https://github.com/user-attachments/assets/de9c4487-e0f2-45a5-8cbe-2904cc47f7bf)
water fix in version 1378.1, i close this bug report, since this is not relevant.
