### ISSUE TITLE
[Request] Window Style

### ISSUE THREAD

**Issue by Wynadorn** [Perchik71/Creation-Kit-Platform-Extended#43]
Say an old video today and what i noticed right away was him having the original window styles,
It'd be amazing if there's a way to force the CK to use this style.

![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/4095127/4d9c716f-31f5-457c-a3fc-df222b57c04b)

I've attempted to do this though the visual styles compatibility setting however with no result. (see [link](https://superuser.com/questions/694734/what-does-compatibility-option-disable-visual-themes-do) for info)

Maybe setting the dialog style though a P/Invoke could do the trick.

**Comment by Perchik71** [comment]
The system must be configured classically, the display of unique classes that do not have an analogue may be different.
![eMxVpsS (1)](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/1d9ac60b-25e1-4c8e-a78e-3071697a65ec)

**Comment by Wynadorn** [comment]
I've done some testing, it can be done via `SetWindowTheme` in [uxtheme.h](https://learn.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-setwindowtheme)

```
HRESULT SetWindowTheme(
  [in] HWND    hwnd,
  [in] LPCWSTR pszSubAppName,
  [in] LPCWSTR pszSubIdList
);
```

`uxtheme::SetWindowTheme(hwnd, "", "");`

**Comment by Perchik71** [comment]
@Wynadorn yep, empty strings will make the classic style, nullptrs will return the default style.

**Comment by Perchik71** [comment]
Challenge...
![2024-05-12_02-02-22](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/8b568f34-be73-44ba-ad71-0895b0a8f764)

**Comment by Wynadorn** [comment]
Ah don't bother unless you want it for yourself, I've settled on running a script to patch the window styles

I do think it looks a lot better, no shadows overlapping

**Comment by Perchik71** [comment]
The frame is too thick...

**Comment by Wynadorn** [comment]
Hmm, unsure what's causing that, it's either the theme metrics, those control the padding on title bars too

But it could also be the form border style

**Comment by Wynadorn** [comment]
Yeah looks like it's the active theme that's causing the border, https://learn.microsoft.com/en-us/windows/win32/controls/themesfileformat-overview

I think the active theme is somewhere in registry, but that value is system wide, it also controls, for example, the padding of the title bar text

I guess uxtheme.dll can be used to overwrite the active theme but I have nooooo idea how

**Comment by Perchik71** [comment]
Preview bugs persist. So the window flicker, not the update in the preview will remain. It is fixed only in the dark theme.

**Comment by Wynadorn** [comment]
b480091 !! 😯 looking forward to try it out

**Comment by Perchik71** [comment]
Now all applications have become web, not native. It doesn't make much sense anymore.
Download the next release and take a look. I don't write in C#.

The system will do better than just uxtheme. :(
