### ISSUE TITLE
GDI Leaks.

### ISSUE THREAD

**Issue by BjornEinherji** [Perchik71/Creation-Kit-Platform-Extended#45]
Thank you for this! Been using it for a while now and it makes a huge difference in the speed and functionality, but I have one question. My CK crashes from time to time, regardless of mods I am working on, but It seems to happen more frequent when editing many exterior cells. After reading some crash logs it seems to be GDI leaks that is the issue. I ran some diagnostics and as soon as the CK hits 10.000 GDI Objects it will crash.

I have tried this on a newly installed computer with a fresh install of Skyrim and creation kit, does not seem to be an issue. Is this a vanilla CK issue or can this perhaps be tied to your extension running with the creation kit?

Here is an example taken from the GDI leak tracker. From what I can see since there are a lot of "Bitmap" entries in the tracker, I will guess the CK does not unload previously read textures or something?
![image](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/16180981/04e782ad-0879-4fd0-bb83-f8a862c7ff66)

**Comment by Perchik71** [comment]
There are many leaks in SSE CK, CKPE solves some of them. Some of Nuukem's works made many years ago are also present here.
Honestly, I didn't even know that there are people who use vanilla CK. He's just terrible, which made people work at SLE CK.

For example: [patch](https://github.com/Perchik71/Creation-Kit-Platform-Extended/blob/master/Creation%20Kit%20Platform%20Extended%20Core/Patches/SSE/MemoryLeakInPreviewWindow.cpp). There is a similar patch for rendering. You can familiarize yourself with all the patches, I have collected them in order so as not to get confused myself.
