### ISSUE TITLE
CKPE crash on papyrus source error

### ISSUE THREAD

**Issue by naaitsab** [Perchik71/Creation-Kit-Platform-Extended#47]
When clicking 'compile' on a Papyrus script. Either from the 'quest stage' tab or on the 'scripts' tab. It causes a hard crash of the  Skyrim CK (no crashlog). I reloaded the mod on the vanilla CK. Doing the same now gave an error that 2 source scripts where missing instead of a hard crash. Resolved that. After that reverted the CKPE patch and it no longer crashes when I click compile. 

Perhaps some unhandled exception causing the program to crash?

CKPE: 0.2-b941
latest CK

**Comment by Perchik71** [comment]
Yes, all crashes are deleted, instead they write to the log and the program goes on to execute, so it crashes.

**Comment by Perchik71** [comment]
This kind of hard crashes the crash signal inside winhttp.dll. 
In the future, I will probably add message processing in the thread .dll.
