### ISSUE TITLE
Crash when running Generate Max Height data for tamriel.

### ISSUE THREAD

**Issue by robertgk2017** [Perchik71/Creation-Kit-Platform-Extended#5]
Loading up just skyrim.esm and generating max height data for Tamriel worldspace, and hitting no to Not reuse existing data, generates for a time, but eventually it throws an assertion and crashes.  Build 538 did not have this crash.

Here is the .zip that it generated.  
[CreationKit.exe_20240105_022004.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/13837241/CreationKit.exe_20240105_022004.zip)

It successfully generates for every other worldspace without issue.

**Comment by robertgk2017** [comment]
Upon furth testing and re-attempts the assertion that gets thrown has the following text.

E:\Projects\Creation-Kit-Platform-Extended\Creation Kit Platform Extended Core\Patches\MemoryManagerPatch.cpp(367):

false

A memory allocation failed.  This is due to memory leaks in the Creation Kit or not having enough free RAM.  Requested chunk size: 1398288 bytes.   I just checked in task manager and its attempting to use over 200 GB of ram.  without CKPE installed running a Generate Max Height data task for the Tamriel worldspace only ends upp using about 5 GB of ram at the most.

**Comment by Perchik71** [comment]
multiplies the pages in the pools, it then I'll put a limiter.

**Comment by Perchik71** [comment]
[vmm-x64.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/13846320/vmm-x64.zip)
maybe fixed

**Comment by Perchik71** [comment]
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
TEXTURES: malehead.nif : MaleHeadIMF is missing a facegen tint map
TEXTURES: malehead.nif : MaleHeadIMF is missing a facegen detail map

The memory manager is disabled. And here there are already mistakes, how you assembled them without CKPE at all, I do not know.

**Comment by Perchik71** [comment]
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
ASSERTION: aSize != 0 (e:\_skyrimhd\code\gamesln\bscore\memorymanager.cpp line 708)
TEXTURES: 1stPersonGauntletsKha_1.nif : KhaHands is missing a specular map
TEXTURES: 1stPersonGauntletsKha_0.nif : KhaHands is missing a specular map

Just a bunch...

**Comment by robertgk2017** [comment]
ive generated max height data for Tamriel with build 538 of CKPE and it didn't use more than about 6 GB of ram for the whole process.  something is definitely messed up.

**Comment by Perchik71** [comment]
hmm.. CK allocates a lot of memory in 0 bytes. need to check the commits.

**Comment by robertgk2017** [comment]
With that updated vmm dll you sent here, it is still memory leaking, but it seems to be a bit slower now.  i have it running an its sitting at 120 GB of ram usage.

**Comment by Perchik71** [comment]
I made a limiter, but I will not add it to the project, the problem is not in it. The problem is that CK allocates a lot of such memory in 0 bytes, somewhere in some commit I made something to do with alignment.

**Comment by Perchik71** [comment]
Although this assembly eats decently. 
![ck](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/07b51c23-21e7-452b-9d63-63969b252b0b)
And this is me xs where he told me about 11400 cell.

**Comment by robertgk2017** [comment]
oh my, yea something definitely odd there.  It shouldn't be using that much memory for something like this.

**Comment by Perchik71** [comment]
Well on 538 build, I caught a crash, but it's not due to lack of memory. But the usual one. but in general, he did not eat more than 40 GB, but he freed up 13 GB, etc. I noticed that the Cell View window is frequently updated and redrawn. In general, I think I can reduce the amount of consumption, but I won't be able to make him eat as little as 6GB, that's for sure.

**Comment by robertgk2017** [comment]
going that low while probably ideal is not realistic.  Whatever optimization that can be done i'll take.  And i'll happily test and report back whatever you try.

**Comment by Perchik71** [comment]
`if that's possible? ` Yep. I need to think about it.

**Comment by Perchik71** [comment]
[patch.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/13847992/patch.zip)
Reduced the total consumption by 4 times, taking into account requests with size 0. However, I still catch a crash in some kind of Cell. Try it yourself.

**Comment by robertgk2017** [comment]
Will do.  I'll report back what happens.

**Comment by robertgk2017** [comment]
Nope, it crashed again.  
[CreationKit.exe_20240105_022004.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/13848198/CreationKit.exe_20240105_022004.zip)

**Comment by Perchik71** [comment]
Creation Kit Platform Extended Runtime: Initialize (Version: 0.1.0.594, OS: 10.0 Build 19045)
Use what I sent you.

**Comment by robertgk2017** [comment]
That is what you sent me.  in that patch.zip i copied both of those dlls to my game folder before running this test

**Comment by Perchik71** [comment]
no, there is a 599 version in the archive. either this is the wrong dump

**Comment by robertgk2017** [comment]
might have been the wrong dump im re running it in the CK and will send you that one when it crashes.

**Comment by robertgk2017** [comment]
Alright here is a fresh one, 
[CreationKit.exe_20240106_044218.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/13848403/CreationKit.exe_20240106_044218.zip)

**Comment by robertgk2017** [comment]
okay ive done a bunch of repeat tests.  for some reason it appears as though data its discarding, it is sending to the Pagefile for eternity.  Assuming this is true, this should not happen, any such data that it is discarding should actually be deleted from memory, both physical and pagefile?  If that makes sense?

**Comment by Perchik71** [comment]
A lot, even by the standards of Fallout 4, where it is necessary to calculate the previs. (240GB). Later, over a cup of tea, in my free time (many my time), I'll look at where they don't free up memory. we'll connect the sniffer, etc.
