### ISSUE TITLE
Crashing after update

### ISSUE THREAD

**Issue by snowboundmage2** [Perchik71/Creation-Kit-Platform-Extended#53]
![image](https://github.com/user-attachments/assets/d997845f-170a-418d-ab10-2782b4accf60)

this crash on window size change
[CreationKitPlatformExtendedCrash.log](https://github.com/user-attachments/files/16318646/CreationKitPlatformExtendedCrash.log)

this crash on load
[CreationKitPlatformExtendedCrash.log](https://github.com/user-attachments/files/16318633/CreationKitPlatformExtendedCrash.log)

It sometimes crashed after loading data, but sometimes it crashed after trying to resize the Objects window
I am running as administrator
end of crashlog says:
```
====== CRASH INFO ======
Exception:
	Code: C0000005
	Address: 00007FF6B7B9B3A4
	Message: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
```

**Comment by Perchik71** [comment]
remove files
TemporaryBehaviorEventInfoOutput.txt
TemporaryClipDataOutput.txt
TemporarySyncAnimDataOutput.txt

all animation errors are related to meshes or these files in one way or another.

**Comment by Perchik71** [comment]
I'll leave it open, I wonder what others will say

**Comment by snowboundmage2** [comment]
> win version?

Windows 10 Home, all updates

**Comment by Perchik71** [comment]
maybe os, resize problem... i use 26100 sdk

**Comment by snowboundmage2** [comment]
> maybe os, resize problem... i use 26100 sdk

For what it's worth, Windows SDK 26100 is completely compatible with Windows 10 19045

**Comment by naaitsab** [comment]
Is MO2 used to start the CK? It seems the combination of CKPE and MO2 triggers the C0000005 constantly on loading larger ESM/ESP files. This is also reported on the Nexus. Someone fixed it by running the CK from the game directory directly. 

A theory I have is that the memory tools of CKPE interfere with the virtual filesystem of MO2 resulting in a memory issue causing the crash.

**Comment by Perchik71** [comment]
there is a patch in CKPE to expand the allowed file size to more than 4GB

**Comment by snowboundmage2** [comment]
> Is MO2 used to start the CK? It seems the combination of CKPE and MO2 triggers the C0000005 constantly on loading larger ESM/ESP files. This is also reported on the Nexus. Someone 'fixed' it by running the CK from the game directory directly.
> 
> A theory I have is that the memory tools of CKPE interfere with the virtual filesystem of MO2 resulting in a memory issue causing the crash.

Yeah, I was/am using MO2. When you use Mo2, you gotta boot the CK through it to load the plugins you want
