### ISSUE TITLE
Cannot move more than 2 objects when snap to Grid is activated

### ISSUE THREAD

**Issue by Mangaclub** [Perchik71/Creation-Kit-Platform-Extended#56]
As soon Snap to Grid is activated, moving more than 2 objects at the same times makes all of the objects snap to the neatrest grid exept the first selected one wich still moves. 
Expected: all objects that are selected move.

**Comment by Perchik71** [comment]
Solution: create file `CreationKitPlatformExtendedFilter.txt` and write `Fake move light`, patch will be excluded, you can see it in the log, but the lighting should not be moved along with the box.
