### ISSUE TITLE
Visual Error in Quest Sub Sections

### ISSUE THREAD

**Issue by carterleseman** [Perchik71/Creation-Kit-Platform-Extended#57]
When I have a quest opened up, and I'm looking through the sub sections, the window seems to duplicate itself in the top left. This happens for the Player Dialogue, Favor Dialogue, Combat, Favors, Detection, Service, and Misc sub sections.

Here's what it looks like:
<img width="921" alt="image" src="https://github.com/user-attachments/assets/d9f4e661-1cea-4890-8447-13dc91b06878">

It sits over the top of the rest of buttons. I can temporarily fix it by clicking a section it doesn't appear on, like Scenes.

I believe I'm on the most recent version of the CK, having installed it from steam not too long ago. I also run the CK through MO2, which shouldn't have any impact, but I don't know.

**Comment by Perchik71** [comment]
increase the window size

**Comment by carterleseman** [comment]
I changed my display scale from 150% to 100%, which fixes the problem, but everything on my screen is too small to read. Ultimately, I'll have to live with this visual glitch.

Sorry, by the way. I think you mentioned this somewhere in your FAQ.

**Comment by Perchik71** [comment]
@carterleseman maximum 125% with some UI/UX issues
