### ISSUE TITLE
SF: Lights Form IDs Missing Light Color

### ISSUE THREAD

**Issue by yak3d** [Perchik71/Creation-Kit-Platform-Extended#58]
Another Starfield specific one, I can also try to look into this. In the SF CK it will set the background of the Light Form ID to the color of the light.

![image](https://github.com/user-attachments/assets/bcdd6b4b-0c54-4f16-89ca-b22f07a1ec7d)

![image](https://github.com/user-attachments/assets/113ff949-809e-4b36-8277-9d97c83cfd35)

**Comment by Perchik71** [comment]
since I don't use CK, what does it mean? each color individually

**Comment by Perchik71** [comment]
I'm not coloring, maybe it's not provided in the Default theme

**Comment by yak3d** [comment]
Yeah its weird, I assume it gets the light color from the form itself, then sets the background to that? But CKPE is stopping that from happening maybe.

**Comment by Perchik71** [comment]
coloring is not a problem... I need to understand what the technology is, why one thing is painted this way and the other in a different way.

**Comment by Perchik71** [comment]
In short, these are colors for Light only. The color itself is equal to specular color. I consider it useless.

**Comment by Perchik71** [comment]
![2024-10-20_05-44-20](https://github.com/user-attachments/assets/d3100493-1f3a-4fc9-96a6-856118123636)
with doublebuffered this see very bad

**Comment by Perchik71** [comment]
![2024-10-20_06-37-06](https://github.com/user-attachments/assets/c9becd6d-e6aa-405c-ac05-859e1e9b8e49)
close

**Comment by DJLegends1011** [comment]
wow you actually fixed it!

**Comment by yak3d** [comment]
That looks great! Thanks for looking into this.
