### ISSUE TITLE
Unsupported version of CK error.

### ISSUE THREAD

**Issue by xon-xoff** [Perchik71/Creation-Kit-Platform-Extended#60]
Using CK v1.13.61.0. According to readme it is supported. Is this correct?

Using the loader from latest release with latest SF files.

Same log opening from MO2 or directly:
Open the config ini file: CreationKitPlatformExtended.ini
Current time: Wednesday 18 Sep 2024 12:49:49 PM Central Daylight Time
CRC32 executable file: 0x6CDE4424
[WARNING] CRC32 does not match any of the known ones, running a version check by signature
[ERROR] The CK version has not been determined

**Comment by Perchik71** [comment]
it is correct, the development is only in 1.13.61.0 version

**Comment by xon-xoff** [comment]
Any chance this will get added to Nexus like the SSE version?

**Comment by Perchik71** [comment]
@xon-xoff  Yes, it will be when the release. Development is underway. I also received an insider that Bethesda is preparing another update, which makes it difficult to keep up to date.

**Comment by xon-xoff** [comment]
https://bethesda.net/en/article/QSbsZDsZVAKO6Ft5LEzAh/starfield-september-update-patch-notes

CK update in beta. Drops on the 30th with DLC.
