### ISSUE TITLE
Request: Change upload dialogs to default to full, rather than small or mid (and not change back)

### ISSUE THREAD

**Issue by JMPZ11** [Perchik71/Creation-Kit-Platform-Extended#61]
Converting to a small or mid master is a destructive process right now, and should not be done by default as it messes up the working project as well, and locks you in. Being locked in should not be the default.

CK's default behavior when uploading to beth.net is to convert your plugin to a small. If you are upload for both pc and xbox, you are given the impression you could have a different type for each platform (doubtful). If you make any changes on the form, like adding an archive, the dialog resets the radio boxes to light.

I propose updating the dialog to default to full, and retain the user's selection.

Thanks!

**Comment by Perchik71** [comment]
Since the ability to edit has been added .esm it has become irrelevant
