### ISSUE TITLE
LinkedRef causes crash

### ISSUE THREAD

**Issue by kristoferblack** [Perchik71/Creation-Kit-Platform-Extended#62]
In the latest build of CKPE, when trying to look at an object with a LinkedRef or trying to add a LinkedRef to an object causes a hard crash of CK. This behavior does not persist when switching back to vanilla CK.

![image](https://github.com/user-attachments/assets/974a8fa8-982f-4823-a34d-ce25ecadc866)

[CreationKit.exe_20240924_162419.zip](https://github.com/user-attachments/files/17117847/CreationKit.exe_20240924_162419.zip)
[CreationKit.exe_20240924_162818.zip](https://github.com/user-attachments/files/17117848/CreationKit.exe_20240924_162818.zip)

**Comment by Perchik71** [comment]
Maybe blocked antivirus.

**Comment by DJLegends1011** [comment]
> Maybe blocked antivirus.
got the same issue as well...

**Comment by Perchik71** [comment]
try crashdump disable

**Comment by Perchik71** [comment]
hmm... I'll think about it.
