### ISSUE TITLE
Automated Builds?

### ISSUE THREAD

**Issue by yak3d** [Perchik71/Creation-Kit-Platform-Extended#67]
We could use GitHub Actions to build each commit to master and build each game bundle, this wouldn't necessarily create it as a release but would be useful for folks wanting to test nightlies.

I would be fine implementing this, if we think it would be helpful.

**Comment by Perchik71** [comment]
I'm not familiar with this, but if it improves the project, you can try it.

**Comment by yak3d** [comment]
> I'm not familiar with this, but if it improves the project, you can try it.

All good, I will get a demo going on my fork and show the results. I did have a couple questions.

1. Can the same winhttp.dll be used for Starfield AND FO4/SSE if CKPE is built with the Release-Qt build config?
2. Can multiple versions of the database file be coupled in the release?

**Comment by Perchik71** [comment]
1. SF use Qt5, Scaleform. Old CK only Scaleform. In this regard, there are two compilation modes, one for SF and the other for the rest. It is redundant to implement Qt for old ones, and it is not entirely clear to me to include static Qt libraries under the license (free), and it will also greatly increase the size of the .dll.
2. database changes from version to version, if something is not in the database, it will not lead to CTD, the patch will not be installed or will not be installed completely.

**Comment by yak3d** [comment]
That makes sense, when I try to build with `Release` not `Release-Qt` I do get errors regarding Qt, for example:

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'QtGui/qwindow.h': No such file or directory	Creation Kit Platform Extended Core	Creation-Kit-Platform-Extended\Creation Kit Platform Extended Core\Editor API\SF\BGSRenderWindowSF.h	7		
```

Not sure if there's another flag I need to flip somewhere to get it to ignore this file since its an SF file.

**Comment by Perchik71** [comment]
git checkout last commit

**Comment by yak3d** [comment]
Thanks @Perchik71! I finally got the builds to a state where I *think* they produce the right output to drop right into the game folder? You can see the artifacts here in my fork https://github.com/yak3d/Creation-Kit-Platform-Extended/actions/runs/11583610712

**Comment by Perchik71** [comment]
Nice work! 
Only plugins are stored in this [folder](https://github.com/Perchik71/Creation-Kit-Platform-Extended/blob/32d827e613f46a3078ecf4d68d6dd751d41b9c79/Creation%20Kit%20Platform%20Extended%20Core/Core/PluginManager.cpp#L66), plugins are here, just as an example, and they do not have to be placed.
Also, you do not need to upload databases that are declared deprecated `creationkit_f4_1_10_943_1`.

**Comment by Perchik71** [comment]
I think the difficulties with the placement of the mod will be handled by the users themselves, since the path may differ.

**Comment by yak3d** [comment]
I think the sample plugin being included was probably a mistake so I'll have it removed.

For the databases where are they marked as deprecated? Or is it always the latest one that we want to include?

I agree installation location/plugins can be handled by the user so I'll make sure the sample isn't present.

**Comment by Perchik71** [comment]
Leaving it for the future, it can create a simple text file with versions...

**Comment by Perchik71** [comment]
`For the databases where are they marked as deprecated? Or is it always the latest one that we want to include?`
hmm... yep, creating a file would be appropriate, it just lists the versions that should be ignored.

**Comment by yak3d** [comment]
I guess my question is how do I know which ones are deprecated and which ones aren't?

**Comment by Perchik71** [comment]
<table>
  <caption>
    At the moment, the platform supports <b>CK</b> version:
  </caption>
  <thead>
    <tr>
      <th scope="col">Version</th>
      <th scope="col">State</th>
      <th scope="col">Version</th>
      <th scope="col">State</th>
      <th scope="col">Version</th>
      <th scope="col">State</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row" colspan="2">Skyrim SE</th>
      <th scope="row" colspan="2">Fallout 4</th>
      <th scope="row" colspan="2">Starfield</th>
    </tr>
    <tr>
      <td>1.5.3.0</td>
      <td>Active</td>
      <td>1.10.162.0</td>
      <td>Active</td>
      <td>1.13.61.0</td>
      <td>Deprecated</td>
    </tr>
    <tr>
      <td>1.5.73.0</td>
      <td>Active</td>
      <td>1.10.943.1</td>
      <td>Deprecated</td>
      <td>1.14.70.0</td>
      <td>Active</td>
    </tr>
    <tr>
      <td>1.6.438.0</td>
      <td>Active</td>
      <td>1.10.982.3</td>
      <td>Active</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>1.6.1130.0</td>
      <td>Active</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
  <tfoot>
    <tr>
      <th scope="row" colspan="2">Status platform</th>
      <th scope="row" colspan="2">Status platform</th>
      <th scope="row" colspan="2">Status platform</th>
    </tr>
    <tr>
      <th scope="row" colspan="2">Stable</th>
      <th scope="row" colspan="2">Stable</th>
      <th scope="row" colspan="2">Stable</th>
    </tr>
  </tfoot>
</table>

**Comment by Perchik71** [comment]
[c636b47](https://github.com/Perchik71/Creation-Kit-Platform-Extended/commit/c636b47469a003ebaa97119880051b48a3f4347b) ty, i added
