### ISSUE TITLE
Starfield: Quest Stages' Menu Papyrus Fragment Buttons Cut Off

### ISSUE THREAD

**Issue by UnknownExplorer13** [Perchik71/Creation-Kit-Platform-Extended#68]
Found a few more cut off buttons. Specifically the `Compile`, `Properties`, and `Edit` buttons at the bottom of the Papyrus Fragments segment of the Quest Stages menu.
![Visible](https://github.com/user-attachments/assets/a4916a14-6b40-41c4-9feb-195245c7b113)
![Cut-off](https://github.com/user-attachments/assets/880a4f3f-f8d4-4ed7-bca5-54c460938206)

**Comment by DJLegends1011** [comment]
oh shit I can't compile lmfao

**Comment by ZeeOgre** [comment]
I just ran into the same problem and was seeing if any other reports on this.

I suspect it's due to the notes in the faq about screen scaling.

I have a 5k primary monitor, and run at 150% scaling, and I also have this problem.

**Comment by DJLegends1011** [comment]
still need this fix...
