### ISSUE TITLE
[FO4] - Version Control Crash

### ISSUE THREAD

**Issue by FlenarnTemp** [Perchik71/Creation-Kit-Platform-Extended#72]
With Version Control enabled, the Creation Kit will crash.

No experimental settings enabled.

[CreationKit.exe_20241109_154521.zip](https://github.com/user-attachments/files/17688524/CreationKit.exe_20241109_154521.zip)

**Comment by Perchik71** [comment]
0000000142F7B530:"Form counts don't match.\r\nFile = %s\r\nForms loaded = %u\r\nForms in file = %u\r\n\r\nDo you want to correct the file header?"

Bethesda screwed up with the types of arguments to this message. You plugin corrupted

**Comment by Perchik71** [comment]
I'll try to fix the message.

**Comment by FlenarnTemp** [comment]
The crash seemingly only occurs when the REFR count goes above the retail limitation of 2.1M.

**Comment by Perchik71** [comment]
![2024-11-09_21-02-58](https://github.com/user-attachments/assets/dc4b7253-480d-40a4-8e1b-cbabc9a52c8b)
There seems to be an error in the file name, however, he always complains about Fallout4. hmm..
