### ISSUE TITLE
[FO4] Version Control Crash

### ISSUE THREAD

**Issue by FlenarnTemp** [Perchik71/Creation-Kit-Platform-Extended#73]
As of commit:

> c4649da

Loading the Creation Kit, with Version Control enabled and `bBSPointerHandleExtremly` set to `true`, the Creation Kit will crash directly after finishing loading.

Crash **only** occurs if the REFR count is above the retail 2^21 limit, otherwise it loads fine.

[CreationKit.exe_20241109_185702.zip](https://github.com/user-attachments/files/17689067/CreationKit.exe_20241109_185702.zip)

**Comment by Perchik71** [comment]
try disable animation
bSkipAnimationBuildData=true
