### ISSUE TITLE
Starfield: Infinite Hang When Initializing Materials

### ISSUE THREAD

**Issue by UnknownExplorer13** [Perchik71/Creation-Kit-Platform-Extended#75]
Not sure if this is just a me issue (feel free to close if it is) but with this latest update the CK hangs infinitely when trying to initialize materials.

This first image was right after updating my GPU to try and solve the issue. The furthest I got was seeing the CK start then immediately crash before the last message in the log.
![Untitled](https://github.com/user-attachments/assets/81b33b09-64cb-49e3-9d8b-f04f5498b54c)

This second one is after I restarted my PC. Similarly, the furthest I got was a white flash of what I assume was the CK starting but again crashing just before the last message in the log.
![Untitled2](https://github.com/user-attachments/assets/6d0a9efc-71d3-48ea-9006-5fa1c3ce88eb)

Even with crash dumps turned on none are generated on account of the splash screen and log window never closing by themselves, forcing me to close them with Task Manager which cancels any opportunity for them to make a crash dump.

**Comment by myenia** [comment]
Exact same issue here. CK itself loads fine. 

[log.txt](https://github.com/user-attachments/files/17839300/log.txt)

**Comment by Perchik71** [comment]
Visit https://github.com/Perchik71/Creation-Kit-Platform-Extended/wiki, disable Load Materials QSplash

**Comment by Perchik71** [comment]
![2024-11-21_07-08-09](https://github.com/user-attachments/assets/c0e9ca2a-5082-4360-9ddf-4abe936ccde0)
For some reason, you missed init materials

**Comment by Perchik71** [comment]
try automate build

**Comment by UnknownExplorer13** [comment]
Still not working on automated build for me but disabling the patch does

**Comment by Perchik71** [comment]
impossible
