### ISSUE TITLE
Crash log - help reading

### ISSUE THREAD

**Issue by sweetinsanity9** [Perchik71/Creation-Kit-Platform-Extended#77]
Here is my crash log --> https://drive.google.com/file/d/1Bt70AltdkAVDy7o3SvU61XuW-jBVCCt_/view?usp=sharing

Could someone help me figure out the issue?

**Comment by Perchik71** [comment]
Localization error, when trying to get the TESFullName string under normal circumstances, the code is never executed, I may delete the function.
