### ISSUE TITLE
Crash when in navmesh mode and pressing 'W' to switch to Navmesh Only View Mode

### ISSUE THREAD

**Issue by robertgk2017** [Perchik71/Creation-Kit-Platform-Extended#87]
These 2 are from an Exterior

[CreationKit.exe_20241202_223054.zip](https://github.com/user-attachments/files/17984774/CreationKit.exe_20241202_223054.zip)
[CreationKit.exe_20241202_222540.zip](https://github.com/user-attachments/files/17984775/CreationKit.exe_20241202_222540.zip)

This one is from an Interior

[CreationKit.exe_20241202_225138.zip](https://github.com/user-attachments/files/17984932/CreationKit.exe_20241202_225138.zip)

**Comment by Vamp-d** [comment]
Same issue happening over here as well

[CreationKit.exe_20241208_044038.zip](https://github.com/user-attachments/files/18050782/CreationKit.exe_20241208_044038.zip)

**Comment by Perchik71** [comment]
@Vamp-d The lamp is identical to the ZXC problem that has already been fixed.

**Comment by Perchik71** [comment]
@robertgk2017 @Vamp-d I finally got to SSE CK and tried changing modes via W, it works fine in the latest version, please do not spam the same problems (issues #89, #81), use the new one

**Comment by Perchik71** [comment]
https://github.com/Perchik71/Creation-Kit-Platform-Extended/actions/runs/12218444754
