### ISSUE TITLE
Request: Allow multiple paths for Papyrus script sources

### ISSUE THREAD

**Issue by metacubed** [Perchik71/Creation-Kit-Platform-Extended#88]
Skyrim modding has a lot of confusion over the "right" path for script sources. Some use "Data\Scripts\Source" while others have "Data\Source\Scripts". This is a major inconvenience for all modders.

I suggest making a property `sScriptSourceFolderList` to replace the existing property `sScriptSourceFolder` in the CK. This way, we could configure:
```
[Papyrus]
sScriptSourceFolderList = ".\Data\Source\Scripts", ".\Data\Scripts\Source"
```
The order of entries in the list can determine the search priority. So in the example above, the Papyrus Manager window will first look at the first entry ".\Data\Source\Scripts", and if not found, move on to the second entry ".\Data\Scripts\Source".

CK does support arrays in the INI file. As an implementation reference, see the property called `sResourceArchiveList` which takes an array of BSA files.

**Comment by Perchik71** [comment]
This is such a basic thing, it has been available for more than 9 years since the time of LE
``` ini
[Papyrus]
sScriptSourceFolder = ".\Data\Scripts\Source\User"
sAdditionalImports = "$(source);.\Data\Scripts\Source\Base"
```
