### ISSUE TITLE
Pressing Z in renderview crashes CK. [Skyrim SE]

### ISSUE THREAD

**Issue by Trico-Everfire** [Perchik71/Creation-Kit-Platform-Extended#89]
As it says on the tin. Pressing Z in the renderview crashes CK. If additional information is required it will be provided.

**Comment by robertgk2017** [comment]
can you provide a crash dump or 2?

**Comment by Trico-Everfire** [comment]
[CreationKit.exe_20241205_015344.zip](https://github.com/user-attachments/files/18023081/CreationKit.exe_20241205_015344.zip)
[CreationKit.exe_20241205_010054.zip](https://github.com/user-attachments/files/18023083/CreationKit.exe_20241205_010054.zip)
[CreationKit.exe_20241205_014555.zip](https://github.com/user-attachments/files/18023084/CreationKit.exe_20241205_014555.zip)
@robertgk2017

**Comment by Perchik71** [comment]
this fixed 840-rc1
