### ISSUE TITLE
Request: An easy way to reuse existing papyrus fragment scripts without needing to open up xEdit. (Skyrim SE)

### ISSUE THREAD

**Issue by TheLovelyServine** [Perchik71/Creation-Kit-Platform-Extended#91]
I would like to ask for an easy way to reuse existing papyrus fragment scripts without needing to open up xEdit, for more convenient quest making on Playstation. If that's possible, it would help a lot for Playstation modders.

**Comment by robertgk2017** [comment]
Fragments are only supposed to be used on their defining record.  Thats why they match filename by Form ID.

**Comment by Perchik71** [comment]
Technically impossible, at the engine limitation level, otherwise, he won't be able to find the fragment.
