### ISSUE TITLE
[SF] - Script Properties Window Issues

### ISSUE THREAD

**Issue by Vaernus12** [Perchik71/Creation-Kit-Platform-Extended#93]
In Starfield, with the current 416.json values for the property window, generally speaking most single property and arrays that have a single field (like an int or float) are working. However, arrays that have two vertical fields (such as requiring a certain form type which has a "Filter" textbox and then a dropdown for the selected form) or three vertical fields (pick reference button, object reference selection which should have a dropdown for cell, and another dropdown for selecting an object reference) were non-functional as the window is not large enough. I have linked a 416.json in here that expands the spacing to accommodate all types in testing.

[416.json](https://github.com/user-attachments/files/18080195/416.json)

However, there are still issues even if getting the spacing correct in the above json. Arrays do not respect the width value of the property edit placeholder. This clips object reference selection and its unusable currently other than using the pick button:
![image](https://github.com/user-attachments/assets/340b69af-5e6e-4bfb-9302-992ebf23e329)

As an example, a single property with object reference picking is fine with the adjustments to 416.json, previously was clipping. Respects the width in the json:
![image](https://github.com/user-attachments/assets/15d36d19-532f-4ba8-be22-41acff79c12e)

Form picking is mostly good, both single property and array, but clips the single property and also has the constrained array element issue like above:
![image](https://github.com/user-attachments/assets/a8c62be8-cab0-4122-a560-96baf37044d1)

Clips most other "value-based" arrays like int but is functional since the value is left-aligned and can be typed in:
![image](https://github.com/user-attachments/assets/995a6e9d-fb2a-464f-bed1-fd0ef43a7807)

**Comment by yak3d** [comment]
@Perchik71 do you have any suggestions for this? If 416 can't be updated to fix it I'm wondering if you have any pointers to start.

**Comment by Perchik71** [comment]
First, 416 accommodates 465 in it, the rest are already in it, 416 and 465 need to be redone, then the dialogue will look nice

**Comment by yak3d** [comment]
@Vaernus12 do you know of a good example to see this clipping?

**Comment by Vaernus12** [comment]
> @Vaernus12 do you know of a good example form in `Starfield.esm` to see this clipping?

0007092C (SQ_Parent) has a bunch of different array-based properties. I haven't checked how struct-based arrays will look. I haven't found a clear array with object references yet, but SQ_Parent has everything else.

**Comment by Perchik71** [comment]
![2024-12-17_02-36-36](https://github.com/user-attachments/assets/701b6787-846d-45d1-bc7d-8f993b326539)

**Comment by Perchik71** [comment]
![2024-12-17_02-38-38](https://github.com/user-attachments/assets/1a4f75c6-a53a-4415-b7d1-a34fc5261e97)

**Comment by Perchik71** [comment]
![2024-12-17_02-55-29](https://github.com/user-attachments/assets/edf1b22a-91a3-4bdb-836a-c7f75c856a2d)
