### ISSUE TITLE
[Starfield] CTD on selecting scene tab when opening quest

### ISSUE THREAD

**Issue by DJLegends1011** [Perchik71/Creation-Kit-Platform-Extended#98]
[CreationKit.exe_20241225_110127.zip](https://github.com/user-attachments/files/18245621/CreationKit.exe_20241225_110127.zip)
Some reason currently having issues in which CK CTD instantly when clicking on scene tab.

Reproducible:
1. load any plugin
2. open any quest preferably a follower/companion
3. open Scene tab
4. CTD occurs and generate dumps

**Comment by Perchik71** [comment]
[CreationKitPlatformExtendedFilter.txt](https://github.com/user-attachments/files/18246488/CreationKitPlatformExtendedFilter.txt)
