### ISSUE TITLE
Fatal Error Unspecified Exception

### ISSUE THREAD

**Issue by samdancer** [Perchik71/Creation-Kit-Platform-Extended#99]
![image](https://github.com/user-attachments/assets/25b199b9-2c15-4a2f-97b4-a328664e1e36)

One of the error dumps (redacted where personal info like usernames is) : 

> Dump Summary
> ------------
> Dump File:	CreationKit.exe_20241226_221423.dmp : C:\Users\REDACTED\AppData\Local\Temp\7zOCFE02BB0\CreationKit.exe_20241226_221423.dmp
> Last Write Time:	12/26/2024 5:14:26 PM
> Process Name:	D:\SteamLibrary\steamapps\common\Skyrim Special Edition\CreationKit.exe 
> Process Architecture:	x64
> Exception Code:	0xc0000005
> Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
> Heap Information:	Not Present
> 
> System Information
> ------------------
> OS Version:	10.0.22631
> CLR Version(s):	
> 
> Modules
> -------
> Module Name	Module Path	Module Version
> -----------	-----------	--------------
> CreationKit.exe	D:\SteamLibrary\steamapps\common\Skyrim Special Edition\CreationKit.exe	1.6.1378.1
> ntdll.dll	C:\Windows\System32\ntdll.dll	6.2.22621.4541
> kernel32.dll	C:\Windows\System32\kernel32.dll	6.2.22621.4391
> KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.2.22621.4541
> user32.dll	C:\Windows\System32\user32.dll	6.2.22621.4541
> win32u.dll	C:\Windows\System32\win32u.dll	6.2.22621.4601
> gdi32.dll	C:\Windows\System32\gdi32.dll	6.2.22621.4036
> gdi32full.dll	C:\Windows\System32\gdi32full.dll	6.2.22621.4391
> msvcp_win.dll	C:\Windows\System32\msvcp_win.dll	6.2.22621.3374
> ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	6.2.22621.3593
> version.dll	C:\Windows\System32\version.dll	6.2.22621.1
> wininet.dll	C:\Windows\System32\wininet.dll	11.0.22621.4541
> msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.22621.2506
> comdlg32.dll	C:\Windows\System32\comdlg32.dll	6.2.22621.4541
> winmm.dll	C:\Windows\System32\winmm.dll	6.2.22621.4541
> combase.dll	C:\Windows\System32\combase.dll	6.2.22621.4541
> advapi32.dll	C:\Windows\System32\advapi32.dll	6.2.22621.4391
> rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.2.22621.4249
> sechost.dll	C:\Windows\System32\sechost.dll	6.2.22621.4541
> SHCore.dll	C:\Windows\System32\SHCore.dll	6.2.22621.4541
> bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.2.22621.2506
> d3d9.dll	C:\Windows\System32\d3d9.dll	6.2.22621.4541
> D3DX9_42.dll	C:\Windows\System32\D3DX9_42.dll	9.27.952.3001
> shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.2.22621.4541
> shell32.dll	C:\Windows\System32\shell32.dll	6.2.22621.4541
> ole32.dll	C:\Windows\System32\ole32.dll	6.2.22621.3958
> oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.2.22621.3672
> uxtheme.dll	C:\Windows\System32\uxtheme.dll	6.2.22621.4541
> dsound.dll	C:\Windows\System32\dsound.dll	6.2.22621.3527
> ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.2.22621.1
> steam_api64.dll	D:\SteamLibrary\steamapps\common\Skyrim Special Edition\steam_api64.dll	7.40.51.27
> setupapi.dll	C:\Windows\System32\setupapi.dll	6.2.22621.2506
> comctl32.dll	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.4541_none_2710d1c57384c085\comctl32.dll	6.10.22621.4541
> dwmapi.dll	C:\Windows\System32\dwmapi.dll	6.2.22621.4541
> ResampleDmo.DLL	C:\Windows\System32\ResampleDmo.DLL	6.2.22621.2506
> X3DAudio1_7.dll	C:\Windows\System32\X3DAudio1_7.dll	9.28.1886.0
> dinput8.dll	C:\Windows\System32\dinput8.dll	6.2.22621.1
> powrprof.dll	C:\Windows\System32\powrprof.dll	6.2.22621.3958
> winmmbase.dll	C:\Windows\System32\winmmbase.dll	6.2.22621.1
> msvcp140.dll	C:\Windows\System32\msvcp140.dll	14.42.34433.0
> winhttp.dll	D:\SteamLibrary\steamapps\common\Skyrim Special Edition\winhttp.dll	0.4.0.952
> VCRUNTIME140.dll	C:\Windows\System32\VCRUNTIME140.dll	14.42.34433.0
> dbghelp.dll	C:\Windows\System32\dbghelp.dll	6.2.22621.3593
> hid.dll	C:\Windows\System32\hid.dll	6.2.22621.1
> dxgi.dll	C:\Windows\System32\dxgi.dll	6.2.22621.4036
> d3d11.dll	C:\Windows\System32\d3d11.dll	6.2.22621.4541
> msdmo.dll	C:\Windows\System32\msdmo.dll	6.2.22621.1
> DXCore.dll	C:\Windows\System32\DXCore.dll	6.2.22621.4541
> VCRUNTIME140_1.dll	C:\Windows\System32\VCRUNTIME140_1.dll	14.42.34433.0
> GdiPlus.dll	C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22621.4541_none_57fbc4aace173a53\GdiPlus.dll	6.2.22621.4541
> msimg32.dll	C:\Windows\System32\msimg32.dll	6.2.22621.2506
> VoltekLib.UnicodeConverter.dll	D:\SteamLibrary\steamapps\common\Skyrim Special Edition\VoltekLib.UnicodeConverter.dll	1.0.0.1
> VoltekLib.Detours.dll	D:\SteamLibrary\steamapps\common\Skyrim Special Edition\VoltekLib.Detours.dll	1.0.0.1
> VoltekLib.MemoryManager.dll	D:\SteamLibrary\steamapps\common\Skyrim Special Edition\VoltekLib.MemoryManager.dll	1.1.0.505
> VoltekLib.RelocationDatabase.dll	D:\SteamLibrary\steamapps\common\Skyrim Special Edition\VoltekLib.RelocationDatabase.dll	1.1.0.45
> vcomp140.dll	C:\Windows\System32\vcomp140.dll	14.42.34433.0
> XINPUT1_3.dll	C:\Windows\System32\XINPUT1_3.dll	9.18.944.0
> winhttp.dll	C:\Windows\System32\winhttp.dll	6.2.22621.4541
> dbgcore.dll	C:\Windows\System32\dbgcore.dll	6.2.22621.1
> imm32.dll	C:\Windows\System32\imm32.dll	6.2.22621.3374
> umpdc.dll	C:\Windows\System32\umpdc.dll	6.2.22621.1
> msftedit.dll	C:\Windows\System32\msftedit.dll	6.2.22621.4541
> usvfs_x64.dll	C:\Modding\MO2\usvfs_x64.dll	0.5.6.1
> windows.storage.dll	C:\Windows\System32\windows.storage.dll	6.2.22621.4601
> WinTypes.dll	C:\Windows\System32\WinTypes.dll	6.2.22621.3810
> kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	6.2.22621.3958
> inputhost.dll	C:\Windows\System32\inputhost.dll	6.2.22621.4541
> CoreMessaging.dll	C:\Windows\System32\CoreMessaging.dll	6.2.22621.4541
> profapi.dll	C:\Windows\System32\profapi.dll	6.2.22621.4541
> bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.2.22621.4317
> CRYPTBASE.DLL	C:\Windows\System32\CRYPTBASE.DLL	6.2.22621.1
> msctf.dll	C:\Windows\System32\msctf.dll	6.2.22621.4601
> TextShaping.dll	C:\Windows\System32\TextShaping.dll	6.2.22621.4541
> textinputframework.dll	C:\Windows\System32\textinputframework.dll	6.2.22621.4541
> oleacc.dll	C:\Windows\System32\oleacc.dll	7.2.22621.1
> clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10941.16384
> Windows.Globalization.dll	C:\Windows\System32\Windows.Globalization.dll	6.2.22621.4541
> globinputhost.dll	C:\Windows\System32\globinputhost.dll	6.2.22621.4541
> Bcp47Langs.dll	C:\Windows\System32\Bcp47Langs.dll	6.2.22621.3672
> Windows.UI.dll	C:\Windows\System32\Windows.UI.dll	6.2.22621.4541
> d3dcompiler_47.dll	C:\Windows\System32\d3dcompiler_47.dll	6.2.22621.2506
> cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.2.22621.3672
> sspicli.dll	C:\Windows\System32\sspicli.dll	6.2.22621.3810
> riched32.dll	C:\Windows\System32\riched32.dll	6.2.22621.2506
> riched20.dll	C:\Windows\System32\riched20.dll	5.31.23.1231
> usp10.dll	C:\Windows\System32\usp10.dll	6.2.22621.1
> msls31.dll	C:\Windows\System32\msls31.dll	3.10.349.0
> webio.dll	C:\Windows\System32\webio.dll	6.2.22621.4391
> FlowchartX64.dll	D:\SteamLibrary\steamapps\common\Skyrim Special Edition\FlowchartX64.dll	4.3.0.0
> winspool.drv	C:\Windows\System32\winspool.drv	6.2.22621.3810
> urlmon.dll	C:\Windows\System32\urlmon.dll	11.0.22621.4169
> iertutil.dll	C:\Windows\System32\iertutil.dll	11.0.22621.4541
> srvcli.dll	C:\Windows\System32\srvcli.dll	6.2.22621.4249
> netutils.dll	C:\Windows\System32\netutils.dll	6.2.22621.2506
> mswsock.dll	C:\Windows\System32\mswsock.dll	6.2.22621.2506
> IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	6.2.22621.1
> winnsi.dll	C:\Windows\System32\winnsi.dll	6.2.22621.1
> nsi.dll	C:\Windows\System32\nsi.dll	6.2.22621.1
> dnsapi.dll	C:\Windows\System32\dnsapi.dll	6.2.22621.4541
> mdnsNSP.dll	C:\Program Files\Bonjour\mdnsNSP.dll	3.1.0.1
> rasadhlp.dll	C:\Windows\System32\rasadhlp.dll	6.2.22621.1
> FWPUCLNT.DLL	C:\Windows\System32\FWPUCLNT.DLL	6.2.22621.4249
> schannel.dll	C:\Windows\System32\schannel.dll	6.2.22621.4541
> ncrypt.dll	C:\Windows\System32\ncrypt.dll	6.2.22621.4317
> ntasn1.dll	C:\Windows\System32\ntasn1.dll	6.2.22621.1
> ncryptsslp.dll	C:\Windows\System32\ncryptsslp.dll	6.2.22621.2506
> crypt32.dll	C:\Windows\System32\crypt32.dll	6.2.22621.4541
> msasn1.dll	C:\Windows\System32\msasn1.dll	6.2.22621.2506
> rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.2.22621.4249
> CoreUIComponents.dll	C:\Windows\System32\CoreUIComponents.dll	6.2.22621.4541
> dpapi.dll	C:\Windows\System32\dpapi.dll	6.2.22621.1
> directxdatabasehelper.dll	C:\Windows\System32\directxdatabasehelper.dll	6.2.22621.4541
> igd10iumd64.dll	C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a2d86d775f73d911\igd10iumd64.dll	26.20.100.7926
> apphelp.dll	C:\Windows\System32\apphelp.dll	6.2.22621.4391
> igdgmm64.dll	C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a2d86d775f73d911\igdgmm64.dll	26.20.100.7926
> igc64.dll	C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a2d86d775f73d911\igc64.dll	26.20.100.7926
> WindowsCodecs.dll	C:\Windows\System32\WindowsCodecs.dll	6.2.22621.4541
> XAudio2_7.dll	C:\Windows\System32\XAudio2_7.dll	9.29.1962.0
> MMDevAPI.dll	C:\Windows\System32\MMDevAPI.dll	6.2.22621.4111
> devobj.dll	C:\Windows\System32\devobj.dll	6.2.22621.2506
> cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	6.2.22621.2506
> resourcepolicyclient.dll	C:\Windows\System32\resourcepolicyclient.dll	6.2.22621.3527
> AudioSes.dll	C:\Windows\System32\AudioSes.dll	6.2.22621.4541
> avrt.dll	C:\Windows\System32\avrt.dll	6.2.22621.3374
> netprofm.dll	C:\Windows\System32\netprofm.dll	6.2.22621.3527
> npmproxy.dll	C:\Windows\System32\npmproxy.dll	6.2.22621.3527
> steamclient64.dll	C:\Users\REDACTED\Desktop\Steam\steamclient64.dll	9.38.28.26
> imagehlp.dll	C:\Windows\System32\imagehlp.dll	6.2.22621.1
> psapi.dll	C:\Windows\System32\psapi.dll	6.2.22621.1
> tier0_s64.dll	C:\Users\REDACTED\Desktop\Steam\tier0_s64.dll	9.38.28.26
> vstdlib_s64.dll	C:\Users\REDACTED\Desktop\Steam\vstdlib_s64.dll	9.38.28.26
> secur32.dll	C:\Windows\System32\secur32.dll	6.2.22621.1
> gameoverlayrenderer64.dll	C:\Users\REDACTED\Desktop\Steam\gameoverlayrenderer64.dll	9.38.28.26
> wintrust.dll	C:\Windows\System32\wintrust.dll	6.2.22621.4541
> explorerframe.dll	C:\Windows\System32\explorerframe.dll	6.2.22621.4601
> 
Only happens when I attempt to open mods and not actual game files

**Comment by Perchik71** [comment]
and? no address crash, disable animation, maybe load
